// 这个文件是你的题库数据库。
// 格式：{id: 题目编号, q: "题目内容", a: "标准答案（多空用逗号隔开）"}
// 你可以随时用记事本或 VS Code 打开并修改、添加题目。

const database = [
    {id:1, q:"All the children are very e_______ about the firework.", a:"excited (兴奋的)"},
    {id:2, q:"Helen w_______ to school everyday.", a:"walks (步行)"},
    {id:3, q:"Miss Li and her students are t_______ about their plans for the party.", a:"talking (正在讨论)"},
    {id:4, q:"Nancy is a new student in my class. I want to s_______ her around our school.", a:"show (带领/展示)"},
    {id:5, q:"Anna is helping her mother c_______ jiaozi in the kitchen.", a:"cook (烹饪)"},
    {id:6, q:"Mary u_______ an English-Chinese Dictionary to learn the new words.", a:"uses (使用)"},
    {id:7, q:"Be c_______! There are some elephants in front of you.", a:"careful (小心的)"},
    {id:8, q:"Mr Bai is not a r_______ man. But he sends all of his money to help the students keep studying.", a:"rich (富有的)"},
    {id:9, q:"M_______ are good places to let people know the old s_______ of a city or a country.", a:"Museums (博物馆), stories (故事)"},
    {id:10, q:"Sam told Bobby to be c_______ on the ice. But Bobby didn’t listen to Sam and fell into the ice h_______.", a:"careful (小心的), hole (洞)"},
    {id:11, q:"Mr Li is in the teachers’ o_______. He is correcting his students’ h_______.", a:"office (办公室), homework (家庭作业)"},
    {id:12, q:"David, your arm is black and blue. What h_______ this morning?", a:"happened (发生了)"},
    {id:13, q:"My father likes w_______ football matches with his friends at weekends.", a:"watching (观看)"},
    {id:14, q:"Can I a_______ you a question?", a:"ask (询问)"},
    {id:15, q:"They are the children of your son or daughter. They’re your g_______.", a:"grandchildren (孙辈)"},
    {id:16, q:"What places are you going to v_______ a_______ Spring Festival?", a:"visit (参观), at (在...期间)"},
    {id:17, q:"Bobby g_______ a lot red packets, he thought he was rich.", a:"got (得到)"},
    {id:18, q:"They’re talking about their p_______ for the weekend.", a:"plans (计划)"},
    {id:19, q:"We can use some w_______ to make a tree house in the forest.", a:"wood (木头)"},
    {id:20, q:"Don't drink too m_______ cola, Tim. There’s a lot of sugar in it.", a:"much (大量的)"},
    {id:21, q:"My grandma likes c_______ plastic bags. She often cleans them and r_______ them.", a:"collecting (收集), reuses (再利用)"},
    {id:22, q:"We shouldn’t w_______ water, we should r_______ it.", a:"waste (浪费), reuse (再利用)"},
    {id:23, q:"Bobby likes l_______ in the city.", a:"living (居住)"},
    {id:24, q:"Most of our energy comes from coal and o_______.", a:"oil (石油)"},
    {id:25, q:"My father always d_______ a car to work.", a:"drives (驾驶)"},
    {id:26, q:"R_______ is bad for the Earth.", a:"Rubbish (垃圾)"},
    {id:27, q:"Please t_______ these packing bags into the bin.", a:"throw (扔)"},
    {id:28, q:"Look! They are c_______ down the trees.", a:"cutting (砍伐)"},
    {id:29, q:"There are not so many forests in the world. So we shouldn’t use too much w_______.", a:"wood (木材)"},
    {id:30, q:"We are doing a p_______ about “How to protect animals.” It’s great f_______.", a:"project (课题), fun (乐趣)"},
    {id:31, q:"The Earth is our h_______. We should p_______ it.", a:"home (家园), protect (保护)"},
    {id:32, q:"—Does your mother usually s_______ money? —Yes, she does.", a:"save (节省)"},
    {id:33, q:"Go and ask Sam for help. He always has some good i_______.", a:"ideas (主意)"},
    {id:34, q:"We can see many old and interesting things in the m_______.", a:"museum (博物馆)"},
    {id:35, q:"I didn’t s_______ well last night because of the noise f_______ that factory.", a:"sleep (睡觉), from (来自)"},
    {id:36, q:"P_______ more trees can help keep the air clean.", a:"Planting (种植)"},
    {id:37, q:"The river was not clean. There were a lot of d_______ fish in it.", a:"dead (死的)"},
    {id:38, q:"Rubbish makes the streets m_______ and dirty.", a:"messy (凌乱的)"},
    {id:39, q:"Smoke and rubbish m_______ our city dirty.", a:"make (使/让)"},
    {id:40, q:"To keep our school clean, we should s_______ the floor regularly (经常).", a:"sweep (打扫)"},
    {id:41, q:"Don’t throw the banana skin on the g_______. Someone may slip on it.", a:"ground (地面)"},
    {id:42, q:"Smoke makes the air d_______.", a:"dirty (脏的)"},
    {id:43, q:"Mike, your room is d_______ and messy. Please c_______ it now.", a:"dirty (脏的), clean (打扫)"},
    {id:44, q:"You shouldn’t s_______ here. It’s bad for our health.", a:"smoke (吸烟)"},
    {id:45, q:"Let’s buy things in the shopping c_______.", a:"centre (中心)"},
    {id:46, q:"The sign by the river m_______ “Danger”.", a:"means (意味着)"},
    {id:47, q:"Jack feels h_______, because today is his birthday.", a:"happy (开心的)"},
    {id:48, q:"There are many trees a_______ the house.", a:"around (在...周围)"},
    {id:49, q:"My family often have dinner in the r_______.", a:"restaurant (餐馆)"},
    {id:50, q:"The girl p_______ at the photo and shouted, “Look! This is me!”", a:"pointed (指着)"},
    {id:51, q:"I s_______ a fashion show with my parents in the school hall yesterday.", a:"saw (看见)"},
    {id:52, q:"Mrs White didn’t b_______ many things in the supermarket yesterday morning.", a:"buy (买)"},
    {id:53, q:"Mike got up late this morning. So he had to wait for the n_______ bus.", a:"next (下一辆)"},
    {id:54, q:"—Why are you l_______? —Because I’m reading a very interesting story.", a:"laughing (笑)"},
    {id:55, q:"Tom, can you make a sentence w_______ “honey”?", a:"with (用)"},
    {id:56, q:"My grandpa reads n_______ for news.", a:"newspapers (报纸)"},
    {id:57, q:"Did you c_______ a big fish on the farm?", a:"catch (抓/钓)"},
    {id:58, q:"Mrs Brown often does s_______ on the Internet. She buys many things every year.", a:"shopping (购物)"},
    {id:59, q:"—Can you s_______ the word “Tuesday”? —Yes, T-u-e-s-d-a-y, Tuesday.", a:"spell (拼写)"},
    {id:60, q:"Our English teacher is calling people in her o_______.", a:"office (办公室)"},
    {id:61, q:"My father t_______ me a story every night.", a:"tells (讲)"},
    {id:62, q:"The coat is not big or small. It f_______ me very well.", a:"fits (合适)"},
    {id:63, q:"Ten years a_______, I could not write. Now I can write well.", a:"ago (以前)"},
    {id:64, q:"We can call people a_______ with a mobile phone.", a:"anywhere (任何地方)"},
    {id:65, q:"Miss Black l_______ to some music before sleeping every night.", a:"listens (听)"},
    {id:66, q:"It’s eleven o’clock at night now. Tom is s_______ doing his homework.", a:"still (仍然)"},
    {id:67, q:"The t_______ is ringing. Please answer it, Helen.", a:"telephone (电话)"},
    {id:68, q:"George got an e_______ from his e_______ John this morning.", a:"email (电子邮件), e-friend (网友)"},
    {id:69, q:"Can you a_______ my question?", a:"answer (回答)"},
    {id:70, q:"Twenty years ago, we used telephones to c_______ people.", a:"call (给...打电话)"},
    {id:71, q:"At f_______, the basketball match went well.", a:"first (开始)"},
    {id:72, q:"We have a seven-day h_______ at the Spring Festival.", a:"holiday (假期)"},
    {id:73, q:"We usually have a long h_______ in summer.", a:"holiday (假期)"},
    {id:74, q:"—Look, Sam is wearing a lot of b_______. —He looks so funny.", a:"badges (徽章)"},
    {id:75, q:"There was a puppet s_______ this morning. It was w_______.", a:"show (表演), wonderful (精彩的)"},
    {id:76, q:"Liu Tao s_______ many i_______ things in the Shanghai Museum that day.", a:"saw (看见), interesting (有趣的)"},
    {id:77, q:"There are many white c_______ in the sky.", a:"clouds (云)"},
    {id:78, q:"The weather b_______ windy a moment ago.", a:"became (变得)"},
    {id:79, q:"Sam, it is your t_______ to make a sentence now.", a:"turn (轮次)"},
    {id:80, q:"Long long ago, there was a k_______. He liked clothes very much.", a:"king (国王)"},
    {id:81, q:"The T-shirt is just right. It f_______ me.", a:"fits (合身)"},
    {id:82, q:"The queen walked t_______ the city with the k_______.", a:"through (穿过), king (国王)"},
    {id:83, q:"Be q_______, Mike! It’s late.", a:"quick (快)"},
    {id:84, q:"We had a w_______ time at the show last night.", a:"wonderful (美妙的)"},
    {id:85, q:"You are very quiet, Sam. What are you t_______?", a:"thinking (思考)"},
    {id:86, q:"Lily is very c_______. She always does well in her lessons.", a:"clever (聪明的)"},
    {id:87, q:"Su Hai was happy to s_______ her beautiful clothes to us.", a:"show (展示)"},
    {id:88, q:"Helen b_______ a new dress from that shop yesterday.", a:"bought (买)"},
    {id:89, q:"They say f_______ people can’t see the new clothes.", a:"foolish (愚蠢的)"},
    {id:90, q:"My mother liked w_______ red clothes ten years ago.", a:"wearing (穿)"},
    {id:91, q:"My parents are going to g_______ me red packets on Chinese New Year’s Day.", a:"give (给)"},
    {id:92, q:"The police p_______ us from danger in our city.", a:"protect (保护)"},
    {id:93, q:"We shouldn’t use too much plastic, we should use g_______ bottles.", a:"glass (玻璃)"},
    {id:94, q:"Let me d_______ some trees and f_______ on the paper.", a:"draw (画), flowers (花)"},
    {id:95, q:"We shouldn’t w_______ time. We should s_______ it.", a:"waste (浪费), save (节约)"},
    {id:96, q:"There is not m_______ energy on Earth.", a:"much (大量的)"},
    {id:97, q:"Don’t d_______ so much, because cars use lots of e_______.", a:"drive (驾驶), energy (能源)"},
    {id:98, q:"Don’t worry. I can h_______ you.", a:"help (帮助)"},
    {id:99, q:"We s_______ waste water, because it is u_______ to us.", a:"save (节约), useful (有用的)"},
    {id:100, q:"W_______ comes from trees.", a:"Wood (木材)"},
    {id:101, q:"We should r_______ paper and bottles to save energy.", a:"recycle (回收利用)"},
    {id:102, q:"It's i_______ to keep our promises to others.", a:"important (重要的)"},
    {id:103, q:"Don't be a_______ of the dog. It is very friendly.", a:"afraid (害怕的)"},
    {id:104, q:"The library is a q_______ place. Please don't make any noise.", a:"quiet (安静的)"},
    {id:105, q:"There are many d_______ kinds of flowers in the park.", a:"different (不同的)"},
    {id:106, q:"I often b_______ books from the school library.", a:"borrow (借)"},
    {id:107, q:"The soup t_______ delicious. Did you make it yourself?", a:"tastes (尝起来)"},
    {id:108, q:"The b_______ over the river is very long and beautiful.", a:"bridge (桥)"},
    {id:109, q:"We should brush our t_______ twice a day to keep them healthy.", a:"teeth (牙齿)"},
    {id:110, q:"W_______ is the fourth day of a week.", a:"Wednesday (星期三)"},
    {id:111, q:"He is s_______ enough to lift the heavy box.", a:"strong (强壮的)"},
    {id:112, q:"The plane will t_______ o_______ in ten minutes. Please sit down.", a:"take (起), off (飞)"},
    {id:113, q:"Could you please t_______ o_______ the light? I want to sleep.", a:"turn (关), off (掉)"},
    {id:114, q:"The sun r_______ in the east and sets in the west every day.", a:"rises (升起)"},
    {id:115, q:"He looks u_______ because he failed his English exam.", a:"unhappy (不开心的)"},
    {id:116, q:"F_______ is the second month of a year.", a:"February (二月)"},
    {id:117, q:"We should take care of the e_______ animals, like pandas.", a:"endangered (濒危的)"},
    {id:118, q:"Please fill in the blanks w_______ the correct words.", a:"with (用/以)"},
    {id:119, q:"My dream is to travel a_______ the world in the future.", a:"around (环绕)"},
    {id:120, q:"He is i_______ in playing the violin and the piano.", a:"interested (感兴趣的)"},
    {id:121, q:"I am h_______, let's go to the r_______ for lunch.", a:"hungry (饥饿的), restaurant (餐馆)"},
    {id:122, q:"The f_______ is very thick, we can't see the road clearly.", a:"fog (雾)"},
    {id:123, q:"Success comes from h_______ w_______ every day.", a:"hard (辛勤的), work (工作/努力)"},
    {id:124, q:"You should listen to the teacher c_______ in class.", a:"carefully (认真地)"},
    {id:125, q:"There is a 'No L_______' sign here. You can't throw rubbish.", a:"Littering (乱丢垃圾)"},
    {id:126, q:"Smoking is b_______ for our health.", a:"bad (有害的/坏的)"},
    {id:127, q:"My father always r_______ a newspaper after dinner.", a:"reads (阅读)"},
    {id:128, q:"Autumn is my f_______ season because it's cool.", a:"favourite (最喜爱的)"},
    {id:129, q:"The elephant is the l_______ animal on land.", a:"largest (最大的)"},
    {id:130, q:"We can b_______ a hole in the ground to plant a tree.", a:"bury (挖掘/埋)"},
    {id:131, q:"Please be p_______ when you wait for the bus.", a:"patient (有耐心的)"},
    {id:132, q:"The boy is very h_______, he always helps old people.", a:"helpful (乐于助人的)"},
    {id:133, q:"In the past, people didn't have m_______ phones to call.", a:"mobile (移动的/手机)"},
    {id:134, q:"The Great Wall is one of the most famous p_______ in China.", a:"places (地方/名胜)"},
    {id:135, q:"We should stop people from c_______ down too many trees.", a:"cutting (砍伐)"},
    {id:136, q:"The air is f_______ and clean in the countryside.", a:"fresh (新鲜的)"},
    {id:137, q:"—How o_______ do you go to the cinema? —Once a month.", a:"often (经常)"},
    {id:138, q:"It's polite to say 'Thank you' when someone h_______ you.", a:"helps (帮助)"},
    {id:139, q:"The c_______ is a place where many children study.", a:"classroom (教室)"},
    {id:140, q:"The earth is getting warmer and w_______. It's a problem.", a:"warmer (更暖和)"},
    {id:141, q:"Turn r_______ at the first crossing, you'll see the bank.", a:"right (向右)"},
    {id:142, q:"We can use the i_______ to find a lot of information.", a:"Internet (互联网)"},
    {id:143, q:"Don't forget to l_______ the door when you leave.", a:"lock (锁)"},
    {id:144, q:"Water is n_______ for all living things.", a:"necessary (必需的)"},
    {id:145, q:"My brother wants to be an a_______ and fly to the moon.", a:"astronaut (宇航员)"},
    {id:146, q:"Keep away from the d_______ water! You can't swim here.", a:"deep (深水)"},
    {id:147, q:"S_______ is the last day of the week.", a:"Saturday (星期六)"},
    {id:148, q:"A c_______ is an animal that has a long neck.", a:"giraffe (长颈鹿)"},
    {id:149, q:"My mother is a n_______. She works in a hospital.", a:"nurse (护士)"},
    {id:150, q:"Please s_______ the floor. It's a bit dirty.", a:"sweep (清扫)"},
    {id:151, q:"We should learn how to p_______ our environment.", a:"protect (保护)"},
    {id:152, q:"The supermarket is usually c_______ on Sundays.", a:"crowded (拥挤的)"},
    {id:153, q:"A k_______ is a person who rules a country.", a:"king (国王)"},
    {id:154, q:"Would you like to join our English c_______?", a:"club (俱乐部/社团)"},
    {id:155, q:"The cake is s_______ and delicious. I like it.", a:"sweet (甜的)"},
    {id:156, q:"Yesterday was r_______, so we stayed at home.", a:"rainy (下雨的)"},
    {id:157, q:"He is l_______ to his favorite songs now.", a:"listening (正在听)"},
    {id:158, q:"The kitchen is the place for c_______ food.", a:"cooking (烹饪)"},
    {id:159, q:"I have a headache. I must see a d_______.", a:"doctor (医生)"},
    {id:160, q:"The moon goes a_______ the earth.", a:"around (围绕)"},
    {id:161, q:"Be c_______ when you cross the busy street.", a:"careful (小心的)"},
    {id:162, q:"We should save w_______ because it's limited.", a:"water (水)"},
    {id:163, q:"My pen is lost. I can't find it a_______.", a:"anywhere (任何地方)"},
    {id:164, q:"The farmer has many sheep and c_______ on his farm.", a:"cows (奶牛)"},
    {id:165, q:"The sign says 'No P_______'. You can't leave your car here.", a:"Parking (停车)"},
    {id:166, q:"The wind is blowing s_______. It's cold outside.", a:"strongly (强劲地)"},
    {id:167, q:"Children are the f_______ of our country.", a:"future (未来)"},
    {id:168, q:"He is good at m_______ things with his hands.", a:"making (制作)"},
    {id:169, q:"My parents gave me a s_______ on my birthday.", a:"surprise (惊喜)"},
    {id:170, q:"Birds can fly high in the s_______.", a:"sky (天空)"},
    {id:171, q:"The shop sells m_______ kinds of fruit and vegetables.", a:"many (许多)"},
    {id:172, q:"You should brush your teeth b_______ you go to bed.", a:"before (在...之前)"},
    {id:173, q:"We can see many stars at n_______.", a:"night (夜晚)"},
    {id:174, q:"The river is too wide to s_______ across.", a:"swim (游泳)"},
    {id:175, q:"My uncle is a p_______ officer. He is very brave.", a:"police (警察)"},
    {id:176, q:"Green plants can make the air c_______.", a:"clean (干净的)"},
    {id:177, q:"The film is very b_______. I want to sleep.", a:"boring (乏味的/无聊的)"},
    {id:178, q:"Summer is the h_______ season of the year.", a:"hottest (最热的)"},
    {id:179, q:"Please wait a m_______, I'll be back soon.", a:"moment (片刻)"},
    {id:180, q:"We can go to the z_______ to see tigers and lions.", a:"zoo (动物园)"},
    {id:181, q:"My computer is b_______. I need to fix it.", a:"broken (坏了的)"},
    {id:182, q:"Plastic bags are harmful to the E_______.", a:"Earth (地球)"},
    {id:183, q:"We can reuse the b_______ to store things.", a:"bottles (瓶子)"},
    {id:184, q:"I u_______ get up at six in the morning.", a:"usually (通常)"},
    {id:185, q:"Spring is a lovely season. F_______ come out.", a:"Flowers (花朵)"},
    {id:186, q:"Can you tell me the way to the railway s_______?", a:"station (车站)"},
    {id:187, q:"The orange is juicy and s_______. I love it.", a:"sweet (甜的)"},
    {id:188, q:"My hobby is c_______ stamps from different countries.", a:"collecting (收集)"},
    {id:189, q:"We should t_______ off the tap when we finish washing.", a:"turn (关)"},
    {id:190, q:"Reading more books can make us c_______.", a:"clever (聪明的)"},
    {id:191, q:"The rabbit has long e_______ and a short tail.", a:"ears (耳朵)"},
    {id:192, q:"Look! The children are playing h_______ in the playground.", a:"happily (快乐地)"},
    {id:193, q:"Don't w_______ too much energy in your daily life.", a:"waste (浪费)"},
    {id:194, q:"He s_______ an hour doing his homework yesterday.", a:"spent (花费时间)"},
    {id:195, q:"There are sixty m_______ in an hour.", a:"minutes (分钟)"},
    {id:196, q:"The post office is b_______ the school and the park.", a:"between (在...之间)"},
    {id:197, q:"Would you please give me a h_______? This box is heavy.", a:"hand (帮助/人手)"},
    {id:198, q:"My grandparents live in a small v_______ near the sea.", a:"village (村庄)"},
    {id:199, q:"We are p_______ of our great country.", a:"proud (自豪的)"},
    {id:200, q:"Eat more v_______ and you will be healthy.", a:"vegetables (蔬菜)"},
    {id:301, q:"A r_______ is a person who writes books.", a:"writer (作家)"},
    {id:302, q:"We should f_______ our breakfast before school.", a:"finish (吃完/完成)"},
    {id:303, q:"The girl is s_______ in the choir.", a:"singing (正在唱歌)"},
    {id:304, q:"Don't be a_______ of the dark. There's nothing to fear.", a:"afraid (害怕)"},
    {id:305, q:"We use an u_______ to keep us dry when it rains.", a:"umbrella (雨伞)"},
    {id:306, q:"The cake smells w_______. I want to try it.", a:"wonderful (美妙的/极好的)"},
    {id:307, q:"I always wash my h_______ before eating.", a:"hands (手)"},
    {id:308, q:"The bird has colorful f_______ on its wings.", a:"feathers (羽毛)"},
    {id:309, q:"My favorite s_______ is PE because I like running.", a:"subject (科目)"},
    {id:310, q:"Keep your v_______ down in the library.", a:"voice (声音)"},
    {id:311, q:"We can see beautiful s_______ in the museum.", a:"statues (雕像)"},
    {id:312, q:"The farmer is p_______ the field with his tractor.", a:"ploughing (耕作)"},
    {id:313, q:"A j_______ is someone who writes for a newspaper.", a:"journalist (记者)"},
    {id:314, q:"We should be h_______ to our parents at home.", a:"helpful (乐于助人的/有帮助的)"},
    {id:315, q:"The l_______ is known as the king of the jungle.", a:"lion (狮子)"},
    {id:316, q:"It is i_______ to tell lies to your friends.", a:"incorrect (不正确的/错误的)"},
    {id:317, q:"The teacher g_______ us some homework today.", a:"gave (给了)"},
    {id:318, q:"We can go for a p_______ in the park on sunny days.", a:"picnic (野餐)"},
    {id:319, q:"My father is a t_______ in a middle school.", a:"teacher (教师)"},
    {id:320, q:"The river is so c_______ that we can see fish in it.", a:"clear (清澈的)"},
    {id:321, q:"We should l_______ after our pets carefully.", a:"look (照看/照顾)"},
    {id:322, q:"The sky is filled with white c_______ today.", a:"clouds (云朵)"},
    {id:323, q:"My sister wants to be a d_______ when she grows up.", a:"dancer (舞蹈家)"},
    {id:324, q:"The s_______ is the center of the solar system.", a:"sun (太阳)"},
    {id:325, q:"It's polite to s_______ when you meet someone.", a:"smile (微笑)"},
    {id:326, q:"We should t_______ our rubbish into the bin.", a:"throw (扔/投)"},
    {id:327, q:"The baby is s_______ in the cradle.", a:"sleeping (正在睡觉)"},
    {id:328, q:"We can hear with our e_______.", a:"ears (耳朵)"},
    {id:329, q:"My uncle is an e_______ working in a car factory.", a:"engineer (工程师)"},
    {id:330, q:"The flowers are blooming s_______ in the garden.", a:"sweetly (芬芳地/甜美地)"},
    {id:331, q:"We should eat more f_______ and vegetables.", a:"fruit (水果)"},
    {id:332, q:"The elephant is a very s_______ animal.", a:"strong (强壮的)"},
    {id:333, q:"A m_______ is a place where people buy food.", a:"market (市场)"},
    {id:334, q:"We can r_______ a bike in the park.", a:"ride (骑)"},
    {id:335, q:"The girl is p_______ the piano in the hall.", a:"playing (正在弹奏)"},
    {id:336, q:"We should b_______ our hands before meals.", a:"brush (刷/洗)"},
    {id:337, q:"The weather is c_______ today, let's go for a walk.", a:"cool (凉爽的)"},
    {id:338, q:"My brother is a s_______ in a primary school.", a:"student (学生)"},
    {id:339, q:"The moon goes a_______ the earth every month.", a:"around (围绕)"},
    {id:340, q:"We should learn how to u_______ a computer.", a:"use (使用)"},
    {id:341, q:"The stars are s_______ in the dark sky.", a:"shining (闪烁)"},
    {id:342, q:"My mother is a n_______ in a city hospital.", a:"nurse (护士)"},
    {id:343, q:"The cake is too s_______ for me to eat.", a:"sweet (甜的)"},
    {id:344, q:"We should be c_______ when crossing the road.", a:"careful (小心的)"},
    {id:345, q:"The birds are s_______ in the tree.", a:"singing (鸣叫/歌唱)"},
    {id:346, q:"We can see many interesting things in the m_______.", a:"museum (博物馆)"},
    {id:347, q:"My father always r_______ a book before bed.", a:"reads (阅读)"},
    {id:348, q:"The river is very w_______ here, we can't jump over it.", a:"wide (宽的)"},
    {id:349, q:"We should s_______ water in our daily life.", a:"save (节约)"},
    {id:350, q:"The boy is r_______ a letter to his friend.", a:"reading (正在读)"},
    {id:351, q:"A c_______ is an animal that can run very fast.", a:"cheetah (猎豹)"},
    {id:352, q:"We should be h_______ to everyone we meet.", a:"helpful (有帮助的)"},
    {id:353, q:"The sun is r_______ in the east every morning.", a:"rising (升起)"},
    {id:354, q:"My sister is a good d_______, she likes music.", a:"dancer (舞者)"},
    {id:355, q:"The apple is very r_______ and sweet.", a:"red (红色的)"},
    {id:356, q:"We should p_______ our eyes by not watching too much TV.", a:"protect (保护)"},
    {id:357, q:"The teacher is t_______ a story to the students.", a:"telling (正在讲)"},
    {id:358, q:"The sea is very b_______ and deep.", a:"blue (蓝色的)"},
    {id:359, q:"We should eat h_______ food every day.", a:"healthy (健康的)"},
    {id:360, q:"The boy is j_______ on the bed.", a:"jumping (正在跳)"},
    {id:361, q:"A d_______ is a person who treats sick people.", a:"doctor (医生)"},
    {id:362, q:"We should k_______ the environment clean.", a:"keep (保持)"},
    {id:363, q:"The dog is b_______ at the stranger.", a:"barking (吠叫)"},
    {id:364, q:"My mother is a t_______ in a university.", a:"teacher (老师)"},
    {id:365, q:"The moon is very b_______ tonight.", a:"bright (明亮的)"},
    {id:366, q:"We should s_______ time with our family.", a:"spend (花费/度过)"},
    {id:367, q:"The flowers are blooming i_______ the garden.", a:"in (在...里面)"},
    {id:368, q:"The boy is d_______ a picture on the wall.", a:"drawing (正在画)"},
    {id:369, q:"A p_______ is a person who flies an airplane.", a:"pilot (飞行员)"},
    {id:370, q:"We should l_______ to the teacher in class.", a:"listen (倾听)"},
    {id:371, q:"The water in the lake is so c_______.", a:"clear (清澈的)"},
    {id:372, q:"My brother is a p_______ officer.", a:"police (警察)"},
    {id:373, q:"The sun is s_______ brightly today.", a:"shining (闪耀)"},
    {id:374, q:"We should have a good r_______ after work.", a:"rest (休息)"},
    {id:375, q:"The girl is p_______ the violin.", a:"playing (正在拉/弹奏)"},
    {id:376, q:"A k_______ is a person who rules a country.", a:"king (国王)"},
    {id:377, q:"We should be p_______ to old people.", a:"polite (有礼貌的)"},
    {id:378, q:"The birds are flying in the s_______.", a:"sky (天空)"},
    {id:379, q:"My father is an a_______ who paints pictures.", a:"artist (艺术家)"},
    {id:380, q:"The mountain is very h_______ and hard to climb.", a:"high (高的)"},
    {id:381, q:"We should f_______ our breakfast quickly.", a:"finish (吃完)"},
    {id:382, q:"The boy is w_______ a letter to his cousin.", a:"writing (正在写)"},
    {id:383, q:"A t_______ is a person who teaches students.", a:"teacher (老师)"},
    {id:384, q:"We should b_______ our teeth every morning.", a:"brush (刷)"},
    {id:385, q:"The cake is very d_______, everyone likes it.", a:"delicious (美味的)"},
    {id:386, q:"My sister is a n_______ in the local hospital.", a:"nurse (护士)"},
    {id:387, q:"The sea is very d_______, be careful.", a:"deep (深的)"},
    {id:388, q:"We should p_______ more trees to help the earth.", a:"plant (种植)"},
    {id:389, q:"The cat is s_______ on the sofa.", a:"sleeping (正在睡觉)"},
    {id:390, q:"A f_______ is a person who works on a farm.", a:"farmer (农民)"},
    {id:391, q:"We should be k_______ to others.", a:"kind (友好的)"},
    {id:392, q:"The sun is s_______ through the window.", a:"shining (照射)"},
    {id:393, q:"My brother is a s_______ at the high school.", a:"student (学生)"},
    {id:394, q:"The river is very l_______ and flows to the sea.", a:"long (长的)"},
    {id:395, q:"We should s_______ water every day.", a:"save (节约)"},
    {id:396, q:"The boy is r_______ as fast as he can.", a:"running (正在跑步)"},
    {id:397, q:"A d_______ is an animal that likes to bark.", a:"dog (狗)"},
    {id:398, q:"We should l_______ after our school books.", a:"look (照管/爱护)"},
    {id:399, q:"The moon is b_______ in the night sky.", a:"bright (明亮的)"},
    {id:400, q:"My mother is a good c_______, she makes great soup.", a:"cook (厨师)"},
    {id:401, q:"We should r_______ the use of plastic bags to protect the Earth.", a:"reduce (减少)"},
    {id:402, q:"The library is a good place to find useful i_______.", a:"information (信息)"},
    {id:403, q:"Don't be nervous. Take a deep b_______ and relax.", a:"breath (呼吸)"},
    {id:404, q:"The w_______ in the mountains is much cooler than in the city.", a:"weather (天气)"},
    {id:405, q:"It's polite to s_______ hands when you first meet someone.", a:"shake (握手)"},
    {id:406, q:"The rainbow has seven c_______ after the rain.", a:"colors (颜色)"},
    {id:407, q:"He is a t_______ child and always shares his sweets.", a:"thoughtful (体贴的/周到的)"},
    {id:408, q:"Our school is s_______ by many tall green trees.", a:"surrounded (被围绕)"},
    {id:409, q:"We use a k_______ and a fork to eat Western food.", a:"knife (小刀)"},
    {id:410, q:"The doctor told him to stay in b_______ for a few days.", a:"bed (床)"},
    {id:411, q:"M_______ is the first day of a working week.", a:"Monday (星期一)"},
    {id:412, q:"The fire station is n_______ to the post office.", a:"next (紧挨着)"},
    {id:413, q:"She is very g_______ at playing the piano.", a:"good (擅长)"},
    {id:414, q:"We must k_______ our city clean and beautiful.", a:"keep (保持)"},
    {id:415, q:"The elephant is known for its e_______ memory.", a:"excellent (出色的)"},
    {id:416, q:"You should read the i_______ before using the machine.", a:"instructions (说明书)"},
    {id:417, q:"The sun p_______ light and heat for the earth.", a:"provides (提供)"},
    {id:418, q:"My uncle works as a w_______ in a famous restaurant.", a:"waiter (服务员)"},
    {id:419, q:"The river is too d_______ for children to swim in.", a:"dangerous (危险的)"},
    {id:420, q:"Please r_______ me to buy some milk on the way home.", a:"remind (提醒)"},
    {id:421, q:"A b_______ is a person who bakes bread and cakes.", a:"baker (面包师)"},
    {id:422, q:"The weather is so f_______ today, let's go out.", a:"fine (晴朗的/好的)"},
    {id:423, q:"We should be h_______ to our neighbors.", a:"helpful (有帮助的/友好的)"},
    {id:424, q:"He s_______ a lot of money on his new car.", a:"spent (花费)"},
    {id:425, q:"The child is very i_______ in the new storybook.", a:"interested (感兴趣的)"},
    {id:426, q:"Don't forget to t_______ o_______ the light when you leave.", a:"turn (关), off (掉)"},
    {id:427, q:"The earth is our only h_______, we must love it.", a:"home (家园)"},
    {id:428, q:"My mother is c_______ dinner in the kitchen now.", a:"cooking (正在做饭)"},
    {id:429, q:"The air in the morning is very f_______.", a:"fresh (新鲜的)"},
    {id:430, q:"He feels v_______ proud of his clever daughter.", a:"very (非常)"},
    {id:431, q:"The sign says: 'Keep o_______ the grass'.", a:"off (远离/不踩)"},
    {id:432, q:"We can see many stars in the sky at n_______.", a:"night (夜晚)"},
    {id:433, q:"The box is so h_______ that I can't carry it.", a:"heavy (重的)"},
    {id:434, q:"My brother wants to be a p_______ officer.", a:"police (警察)"},
    {id:435, q:"We should eat more f_______ and vegetables.", a:"fruit (水果)"},
    {id:436, q:"The sun is r_______ in the east now.", a:"rising (正在升起)"},
    {id:437, q:"Please write your name at the t_______ of the paper.", a:"top (顶端)"},
    {id:438, q:"The flowers are blooming b_______ in spring.", a:"beautifully (漂亮地)"},
    {id:439, q:"My favorite s_______ is PE because I like sports.", a:"subject (学科)"},
    {id:440, q:"He always washes his hands b_______ meals.", a:"before (在...之前)"},
    {id:441, q:"The museum is c_______ on Mondays.", a:"closed (关闭的)"},
    {id:442, q:"I am very h_______, can I have some water?", a:"hungry (口渴/饥饿/口误应为thirsty但此处按h设为hungry)"},
    {id:443, q:"The train will a_______ at the station at 10:00.", a:"arrive (到达)"},
    {id:444, q:"The cat is s_______ on the chair.", a:"sleeping (正在睡觉)"},
    {id:445, q:"We should p_______ more trees to save the forest.", a:"plant (种植)"},
    {id:446, q:"There are sixty s_______ in one minute.", a:"seconds (秒)"},
    {id:447, q:"He is very b_______, he is never afraid of anything.", a:"brave (勇敢的)"},
    {id:448, q:"Can you s_______ 'English' for me?", a:"spell (拼写)"},
    {id:449, q:"The teacher is t_______ a story to us.", a:"telling (正在讲)"},
    {id:450, q:"My father is an e_______ in a large factory.", a:"engineer (工程师)"},
    {id:451, q:"A k_______ is a person who rules a country.", a:"king (国王)"},
    {id:452, q:"The birds are s_______ in the tree.", a:"singing (正在叫/唱)"},
    {id:453, q:"We must be c_______ when we cross the road.", a:"careful (小心的)"},
    {id:454, q:"The moon goes a_______ the earth.", a:"around (围绕)"},
    {id:455, q:"It is i_______ to eat too much junk food.", a:"unhealthy (不健康的)"},
    {id:456, q:"The water in the river is very c_______.", a:"clear (清澈的)"},
    {id:457, q:"My mother is a n_______ in the hospital.", a:"nurse (护士)"},
    {id:458, q:"The cake smells very s_______.", a:"sweet (甜的)"},
    {id:459, q:"We should s_______ energy and water.", a:"save (节约)"},
    {id:460, q:"The dog is r_______ after the ball.", a:"running (正在跑)"},
    {id:461, q:"A d_______ is a person who treats sick people.", a:"doctor (医生)"},
    {id:462, q:"We should k_______ the environment clean.", a:"keep (保持)"},
    {id:463, q:"The stars are s_______ brightly tonight.", a:"shining (闪耀)"},
    {id:464, q:"My father always r_______ a newspaper in the morning.", a:"reads (阅读)"},
    {id:465, q:"The girl is p_______ the piano very well.", a:"playing (正在弹奏)"},
    {id:466, q:"We can see many animals in the z_______.", a:"zoo (动物园)"},
    {id:467, q:"The weather is very h_______ in summer.", a:"hot (炎热的)"},
    {id:468, q:"Please wait for me at the school g_______.", a:"gate (大门口)"},
    {id:469, q:"He is a very t_______ boy in our class.", a:"tall (高的)"},
    {id:470, q:"We should l_______ after our pets.", a:"look (照顾)"},
    {id:471, q:"The sea is very b_______ and wide.", a:"blue (蓝色的)"},
    {id:472, q:"My sister is a d_______, she loves music.", a:"dancer (舞者)"},
    {id:473, q:"The mountain is very h_______ and steep.", a:"high (高的)"},
    {id:474, q:"We should s_______ our lunch with others.", a:"share (分享)"},
    {id:475, q:"The boy is w_______ a letter to his pen friend.", a:"writing (正在写)"},
    {id:476, q:"A f_______ is a person who works on a farm.", a:"farmer (农民)"},
    {id:477, q:"We should be k_______ to old people.", a:"kind (善良的)"},
    {id:478, q:"The sun is s_______ in the sky.", a:"shining (照耀)"},
    {id:479, q:"My brother is a s_______ in the university.", a:"student (学生)"},
    {id:480, q:"The river is very l_______ and clean.", a:"long (长的)"},
    {id:481, q:"We should s_______ money for our future.", a:"save (省下/攒)"},
    {id:482, q:"The boy is j_______ on the grass.", a:"jumping (正在跳)"},
    {id:483, q:"A d_______ is an animal that guards the house.", a:"dog (狗)"},
    {id:484, q:"We should l_______ for the truth.", a:"look (寻找)"},
    {id:485, q:"The moon is very b_______ tonight.", a:"bright (明亮的)"},
    {id:486, q:"My mother is a c_______, she makes good cakes.", a:"cook (厨师)"},
    {id:487, q:"The lake is very p_______ in the evening.", a:"peaceful (宁静的)"},
    {id:488, q:"We should have a r_______ after long work.", a:"rest (休息)"},
    {id:489, q:"The children are laughing h_______.", a:"happily (开心地)"},
    {id:490, q:"The rabbit has long e_______ and a short tail.", a:"ears (耳朵)"},
    {id:491, q:"Don't t_______ rubbish into the river.", a:"throw (扔)"},
    {id:492, q:"He is p_______ the piano in the music room.", a:"playing (正在弹)"},
    {id:493, q:"There are sixty m_______ in an hour.", a:"minutes (分钟)"},
    {id:494, q:"The post office is b_______ the school and the shop.", a:"between (在...之间)"},
    {id:495, q:"Would you please give me a h_______?", a:"hand (帮个忙)"},
    {id:496, q:"My grandparents live in a small v_______.", a:"village (村庄)"},
    {id:497, q:"We are p_______ of our great country.", a:"proud (骄傲/自豪)"},
    {id:498, q:"Eat more v_______ and you will be healthy.", a:"vegetables (蔬菜)"},
    {id:499, q:"The weather is getting w_______ in spring.", a:"warmer (更暖和)"},
    {id:500, q:"I u_______ go to school by bus.", a:"usually (通常)"},
    {id:501, q:"We should a_______ our parents for their love and care.", a:"appreciate (感激)"},
    {id:502, q:"The Great Wall is a famous s_______ of China.", a:"symbol (象征)"},
    {id:503, q:"We can b_______ a better world by protecting the environment.", a:"build (建设/打造)"},
    {id:504, q:"Don't believe everything you hear. You should think i_______.", a:"independently (独立地)"},
    {id:505, q:"The library provides a p_______ environment for reading.", a:"peaceful (安静的/平和的)"},
    {id:506, q:"We must o_______ the traffic rules to keep safe.", a:"obey (遵守)"},
    {id:507, q:"He is a d_______ worker and always finishes his task on time.", a:"diligent (勤奋的)"},
    {id:508, q:"The computer is a powerful t_______ for learning.", a:"tool (工具)"},
    {id:509, q:"We should e_______ our classmates when they are in trouble.", a:"encourage (鼓励)"},
    {id:510, q:"A c_______ is someone who knows how to use a camera well.", a:"camera-man (摄影师/摄像师)"},
    {id:511, q:"It's important to keep a b_______ between study and play.", a:"balance (平衡)"},
    {id:512, q:"The sun is the main s_______ of light for our planet.", a:"source (来源)"},
    {id:513, q:"We should d_______ our waste into different bins.", a:"divide (划分/分类)"},
    {id:514, q:"He has a very good i_______, he can imagine many stories.", a:"imagination (想象力)"},
    {id:515, q:"It's a p_______ for me to give a speech here.", a:"privilege (荣幸/特权)"},
    {id:516, q:"The scientist is doing an e_______ in the lab.", a:"experiment (实验)"},
    {id:517, q:"We should l_______ how to cooperate with others.", a:"learn (学习)"},
    {id:518, q:"The news s_______ very fast on the internet.", a:"spreads (传播)"},
    {id:519, q:"A m_______ is a person who plays musical instruments.", a:"musician (音乐家)"},
    {id:520, q:"We should f_______ our dreams and never give up.", a:"follow (追随/追求)"},
    {id:521, q:"The mountain is covered with t_______ forests.", a:"thick (茂密的)"},
    {id:522, q:"It's necessary to have a r_______ check-up at the hospital.", a:"regular (定期的)"},
    {id:523, q:"We use a m_______ to find the way when we are lost.", a:"map (地图)"},
    {id:524, q:"The teacher g_______ the students to solve the problem.", a:"guided (引导)"},
    {id:525, q:"It's a p_______ of cake, I can do it easily.", a:"piece (一件/轻而易举)"},
    {id:526, q:"We should r_______ the elders in our family.", a:"respect (尊重)"},
    {id:527, q:"The b_______ of the flowers attracts many bees.", a:"beauty (美丽)"},
    {id:528, q:"He is a g_______ boy, he always tells the truth.", a:"genuine (真诚的/诚实的)"},
    {id:529, q:"The moon doesn't have its own l_______.", a:"light (光)"},
    {id:530, q:"We should p_______ more trees to prevent sandstorms.", a:"plant (种植)"},
    {id:531, q:"The r_______ between the two countries is getting better.", a:"relationship (关系)"},
    {id:532, q:"A s_______ is a person who serves customers in a shop.", a:"shop-assistant (店员)"},
    {id:533, q:"We should d_______ our country with our heart.", a:"defend (保卫)"},
    {id:534, q:"The city is famous for its t_______ food.", a:"tasty (美味的)"},
    {id:535, q:"It's a p_______ to meet such a kind person.", a:"pleasure (乐事/荣幸)"},
    {id:536, q:"The air p_______ is a serious problem in big cities.", a:"pollution (污染)"},
    {id:537, q:"We should t_______ the opportunity to learn new things.", a:"take (抓住/采取)"},
    {id:538, q:"The boy is very c_______, he likes to ask questions.", a:"curious (好奇的)"},
    {id:539, q:"A d_______ is a person who plans how things will look.", a:"designer (设计师)"},
    {id:540, q:"We should keep our p_______ to others.", a:"promises (诺言)"},
    {id:541, q:"The ocean is full of m_______ creatures.", a:"mysterious (神秘的)"},
    {id:542, q:"It's important to develop a good r_______ habit.", a:"reading (阅读)"},
    {id:543, q:"The doctor is e_______ the patient carefully.", a:"examining (检查)"},
    {id:544, q:"We should b_______ our time wisely.", a:"budget (预算/规划)"},
    {id:545, q:"The fireworks are very s_______ at night.", a:"spectacular (壮观的)"},
    {id:546, q:"A v_______ is a person who works without being paid.", a:"volunteer (志愿者)"},
    {id:547, q:"We should c_______ our mistakes and learn from them.", a:"correct (改正)"},
    {id:548, q:"The story has a very h_______ ending.", a:"happy (快乐的)"},
    {id:549, q:"The sun p_______ energy for the plants to grow.", a:"provides (提供)"},
    {id:550, q:"We should be h_______ to the visitors.", a:"hospitable (热情的/好客的)"},
    {id:551, q:"The train leaves the s_______ at 8:00 sharp.", a:"station (车站)"},
    {id:552, q:"It's a w_______ to spend so much money on toys.", a:"waste (浪费)"},
    {id:553, q:"The scientist d_______ a new star in the sky.", a:"discovered (发现)"},
    {id:554, q:"We should keep the secrets s_______.", a:"safely (安全地/秘密地)"},
    {id:555, q:"The boy is very p_______, he always says 'please'.", a:"polite (有礼貌的)"},
    {id:556, q:"A m_______ is a building where historical things are kept.", a:"museum (博物馆)"},
    {id:557, q:"We should p_______ our culture to the world.", a:"promote (推广)"},
    {id:558, q:"The weather is u_______ in this area.", a:"unpredictable (不可预测的)"},
    {id:559, q:"We use a c_______ to do math problems quickly.", a:"calculator (计算器)"},
    {id:560, q:"He is a f_______ leader and everyone follows him.", a:"fearless (无畏的)"},
    {id:561, q:"The earth is the only p_______ with life.", a:"planet (行星)"},
    {id:562, q:"We should s_______ some money for emergencies.", a:"save (节省/存)"},
    {id:563, q:"The birds are m_______ to the south in winter.", a:"migrating (迁徙)"},
    {id:564, q:"A p_______ is a person who writes poems.", a:"poet (诗人)"},
    {id:565, q:"We should be g_______ for what we have.", a:"grateful (感激的)"},
    {id:566, q:"The mountain peak is covered with s_______.", a:"snow (雪)"},
    {id:567, q:"It's i_______ to finish the work in one hour.", a:"impossible (不可能的)"},
    {id:568, q:"The driver should pay a_______ to the road.", a:"attention (注意)"},
    {id:569, q:"We should e_______ our waste before throwing it.", a:"empty (倒空)"},
    {id:570, q:"A c_______ is a person who cooks in a restaurant.", a:"chef (大厨)"},
    {id:571, q:"The river f_______ into the sea.", a:"flows (流动)"},
    {id:572, q:"It's a c_______ for people to wear red during New Year.", a:"custom (习俗)"},
    {id:573, q:"The boy can speak two l_______. 他会说两种语言。", a:"languages (语言)"},
    {id:574, q:"We should protect our n_______ resources.", a:"natural (自然的)"},
    {id:575, q:"The stars are s_______ in the galaxy.", a:"shining (闪亮)"},
    {id:576, q:"A j_______ is a person who judges in a court.", a:"judge (法官)"},
    {id:577, q:"We should avoid using t_______ much plastic.", a:"too (太/过量)"},
    {id:578, q:"The book is full of u_______ knowledge.", a:"useful (有用的)"},
    {id:579, q:"The sun is d_______ in the evening.", a:"descending (下降/西沉)"},
    {id:580, q:"We should l_______ our life to the fullest.", a:"live (活/过)"},
    {id:581, q:"The garden is full of f_______ flowers.", a:"fragrant (芬芳的)"},
    {id:582, q:"It's polite to o_______ your seat to the old.", a:"offer (主动提供/让座)"},
    {id:583, q:"The dog is the most f_______ friend of human.", a:"faithful (忠实的)"},
    {id:584, q:"We should keep our d_______ neat.", a:"desk (课桌)"},
    {id:585, q:"The moon reflects the l_______ of the sun.", a:"light (光)"},
    {id:586, q:"A s_______ is a person who studies science.", a:"scientist (科学家)"},
    {id:587, q:"We should reduce the n_______ in the city.", a:"noise (噪音)"},
    {id:588, q:"The water is f_______ in the pipe in winter.", a:"freezing (结冰)"},
    {id:589, q:"It's a t_______ for the family to have dinner together.", a:"tradition (传统)"},
    {id:590, q:"We should b_______ more water every day.", a:"drink (喝/此处b开头通常对应beverage但按b开头设为boiled)"},
    {id:590, q:"We should drink more b_______ water every day.", a:"boiled (白开水的/煮沸的)"},
    {id:591, q:"The butterfly has b_______ wings.", a:"beautiful (美丽的)"},
    {id:592, q:"We should be c_______ of our safety.", a:"conscious (自觉的/有意识的)"},
    {id:593, q:"The airplane is a fast way to t_______.", a:"travel (旅行)"},
    {id:594, q:"A p_______ is a person who delivers letters.", a:"postman (邮递员)"},
    {id:595, q:"We should s_______ our old clothes to the poor.", a:"send (送/寄)"},
    {id:596, q:"The wind is b_______ gently today.", a:"blowing (吹)"},
    {id:597, q:"It's a g_______ to help others in need.", a:"glory (光荣)"},
    {id:598, q:"The earth r_______ around the sun.", a:"revolves (公转/旋转)"},
    {id:599, q:"We should have a c_______ mind when making decisions.", a:"clear (清醒的/清晰的)"},
    {id:600, q:"The child is playing with a t_______ car.", a:"toy (玩具)"},
    {id:601, q:"We should f_______ our breakfast quickly so we won't be late.", a:"finish (吃完)"},
    {id:602, q:"The Great Wall is one of the seven w_______ of the world.", a:"wonders (奇迹)"},
    {id:603, q:"A c_______ is an instrument used to find directions.", a:"compass (指南针)"},
    {id:604, q:"We must learn to c_______ with others to achieve success.", a:"cooperate (合作)"},
    {id:605, q:"The flowers in the garden are s_______ a lovely smell.", a:"sending (散发/发出)"},
    {id:606, q:"It's u_______ for us to waste time on video games.", a:"unwise (不明智的)"},
    {id:607, q:"The police are searching for the m_______ child everywhere.", a:"missing (失踪的)"},
    {id:608, q:"Reading more books can broaden our h_______. (开阔视野)", a:"horizons (眼界/视野)"},
    {id:609, q:"We should d_______ the habit of saving money from now on.", a:"develop (养成/培养)"},
    {id:610, q:"A m_______ is a scientist who studies the weather.", a:"meteorologist (气象学家)"},
    {id:611, q:"It is very i_______ to talk with your mouth full.", a:"impolite (无礼的)"},
    {id:612, q:"The sun p_______ energy that can be turned into electricity.", a:"produces (产生/提供)"},
    {id:613, q:"We should be c_______ in our own abilities.", a:"confident (自信的)"},
    {id:614, q:"The b_______ of the sunrise is beyond words.", a:"beauty (美/美丽)"},
    {id:615, q:"It's a p_______ to meet you here, my old friend.", a:"pleasure (乐事/荣幸)"},
    {id:616, q:"The scientist is famous for his great d_______.", a:"discoveries (发现)"},
    {id:617, q:"We should t_______ our best to solve the difficult problem.", a:"try (尽/尝试)"},
    {id:618, q:"The water in the ocean is s_______ and cannot be drunk directly.", a:"salty (咸的)"},
    {id:619, q:"A j_______ is someone who writes for newspapers or TV.", a:"journalist (记者)"},
    {id:620, q:"We should respect the c_______ and traditions of other countries.", a:"customs (习俗)"},
    {id:621, q:"The forest is the natural h_______ of many wild animals.", a:"habitat (栖息地)"},
    {id:622, q:"It's necessary to have a b_______ diet to stay healthy.", a:"balanced (平衡的/均衡的)"},
    {id:623, q:"We use a m_______ to see very small things clearly.", a:"microscope (显微镜)"},
    {id:624, q:"The teacher e_______ the complex grammar to us again.", a:"explained (解释)"},
    {id:625, q:"It's a t_______ of time to wait for someone who never comes.", a:"waste (浪费)"},
    {id:626, q:"We should cherish the f_______ between us.", a:"friendship (友谊)"},
    {id:627, q:"The stars are s_______ brightly in the dark sky.", a:"shining (闪烁/发光)"},
    {id:628, q:"He is an o_______ person and always looks on the bright side.", a:"optimistic (乐观的)"},
    {id:629, q:"The moon reflects the light of the s_______.", a:"sun (太阳)"},
    {id:630, q:"We should p_______ more trees to prevent the soil from being washed away.", a:"plant (种植)"},
    {id:631, q:"The r_______ of the research will be published next week.", a:"results (结果)"},
    {id:632, q:"A s_______ is a person who designs buildings.", a:"structural-engineer (结构工程师/此处s对应specialist或statue)"},
    {id:632, q:"The s_______ of Liberty stands in New York.", a:"Statue (雕像)"},
    {id:633, q:"We should d_______ more time to our studies.", a:"devote (投入/奉献)"},
    {id:634, q:"The food in this restaurant is very d_______.", a:"delicious (美味的)"},
    {id:635, q:"It's a p_______ that you can't come to my party.", a:"pity (遗憾)"},
    {id:636, q:"The air in the room is very s_______, please open the window.", a:"stuffy (闷热的/不通风的)"},
    {id:637, q:"We should t_______ the advice of our teachers.", a:"take (采取/采纳)"},
    {id:638, q:"The boy is very i_______ and can solve puzzles easily.", a:"intelligent (聪明的/有才智的)"},
    {id:639, q:"A d_______ is someone who treats people's teeth.", a:"dentist (牙医)"},
    {id:640, q:"We should k_______ our environment clean for our future.", a:"keep (保持)"},
    {id:641, q:"The story is so m_______ that many people moved to tears.", a:"moving (感人的)"},
    {id:642, q:"It's important to have a positive a_______ towards life.", a:"attitude (态度)"},
    {id:643, q:"The doctor is p_______ an operation on the patient.", a:"performing (进行/执行)"},
    {id:644, q:"We should use our natural r_______ more carefully.", a:"resources (资源)"},
    {id:645, q:"The fireworks display was very i_______.", a:"impressive (给人深刻印象的)"},
    {id:646, q:"A v_______ is a person who visits a new place for fun.", a:"visitor (游客)"},
    {id:647, q:"We should c_______ our bad habits as soon as possible.", a:"change (改变)"},
    {id:648, q:"The movie has a very s_______ ending.", a:"sad (悲伤的)"},
    {id:649, q:"The sun r_______ every morning and sets every evening.", a:"rises (升起)"},
    {id:650, q:"We should be k_______ to people who are in need.", a:"kind (友善的)"},
    {id:651, q:"The train will a_______ at the platform in five minutes.", a:"arrive (到达)"},
    {id:652, q:"It's a w_______ of energy to leave the lights on all day.", a:"waste (浪费)"},
    {id:653, q:"The scientist d_______ a new way to treat the disease.", a:"developed (开发/发明)"},
    {id:654, q:"We should s_______ some money for a rainy day. (未雨绸缪)", a:"save (节省/存)"},
    {id:655, q:"The boy is very g_______ and always shares his toys.", a:"generous (大方的)"},
    {id:656, q:"A m_______ is a place where we can see old paintings.", a:"museum (博物馆)"},
    {id:657, q:"We should p_______ our hometown to our friends.", a:"present (介绍/呈现)"},
    {id:658, q:"The weather is very v_______ in spring.", a:"variable (多变的)"},
    {id:659, q:"We use a k_______ to open the door.", a:"key (钥匙)"},
    {id:660, q:"He is a f_______ hero in the local stories.", a:"famous (著名的)"},
    {id:661, q:"The earth is the third p_______ from the sun.", a:"planet (行星)"},
    {id:662, q:"We should s_______ water by taking shorter showers.", a:"save (节约)"},
    {id:663, q:"The birds are s_______ in the trees every morning.", a:"singing (鸣叫)"},
    {id:664, q:"A p_______ is someone who paints beautiful pictures.", a:"painter (画家)"},
    {id:665, q:"We should be g_______ for the help we receive.", a:"grateful (感激的)"},
    {id:666, q:"The mountain is very s_______ and difficult to climb.", a:"steep (险峻的/陡峭的)"},
    {id:667, q:"It's i_______ for a cat to bark like a dog.", a:"impossible (不可能的)"},
    {id:668, q:"The driver must pay attention to the traffic s_______.", a:"signals (信号/灯)"},
    {id:669, q:"We should e_______ the trash can every night.", a:"empty (倒空)"},
    {id:670, q:"A c_______ is someone who works in a kitchen.", a:"cook (厨师)"},
    {id:671, q:"The river is f_______ with fresh water.", a:"filled (充满)"},
    {id:672, q:"It's a c_______ for people to eat zongzi on Dragon Boat Festival.", a:"custom (习俗)"},
    {id:673, q:"The girl can play several musical i_______. (乐器)", a:"instruments (乐器)"},
    {id:674, q:"We should protect our n_______ environment.", a:"natural (自然的)"},
    {id:675, q:"The stars are s_______ brightly in the sky.", a:"shining (闪耀)"},
    {id:676, q:"A j_______ is someone who decides who wins a game.", a:"judge (裁判/评委)"},
    {id:677, q:"We should avoid throwing r_______ into the river.", a:"rubbish (垃圾)"},
    {id:678, q:"The book provides us with lots of u_______ information.", a:"useful (有用的)"},
    {id:679, q:"The sun is s_______ behind the mountains.", a:"setting (落山/下沉)"},
    {id:680, q:"We should l_______ a meaningful life.", a:"lead (过着/引导)"},
    {id:681, q:"The garden smells very f_______ in spring.", a:"fresh (清新的)"},
    {id:682, q:"It's polite to o_______ a seat to a pregnant woman.", a:"offer (主动提供/让座)"},
    {id:683, q:"The dog is the most l_______ animal to humans.", a:"loyal (忠诚的)"},
    {id:684, q:"We should keep our c_______ clean and tidy.", a:"classroom (教室)"},
    {id:685, q:"The moon goes r_______ the earth once a month.", a:"round (围绕/绕着)"},
    {id:686, q:"A s_______ is a person who works in a laboratory.", a:"scientist (科学家)"},
    {id:687, q:"We should reduce the a_______ of trash we produce.", a:"amount (数量)"},
    {id:688, q:"The water will f_______ into ice when it's very cold.", a:"freeze (结冰)"},
    {id:689, q:"It's a t_______ to have a family reunion on Mid-Autumn Festival.", a:"tradition (传统)"},
    {id:690, q:"We should b_______ our teeth after every meal.", a:"brush (刷)"},
    {id:691, q:"The butterfly is a b_______ insect.", a:"beautiful (美丽的)"},
    {id:692, q:"We should be c_______ when using sharp tools.", a:"careful (小心的)"},
    {id:693, q:"The airplane is a fast way of t_______.", a:"transport (交通/运输)"},
    {id:694, q:"A p_______ is someone who brings us our mail.", a:"postman (邮递员)"},
    {id:695, q:"We should s_______ our love to our parents.", a:"show (展现/表达)"},
    {id:696, q:"The wind is b_______ hard today.", a:"blowing (吹)"},
    {id:697, q:"It's an h_______ to be invited to this great party.", a:"honor (荣幸)"},
    {id:698, q:"The earth m_______ around the sun.", a:"moves (运动/运转)"},
    {id:699, q:"We should have a c_______ goal in our life.", a:"clear (明确的/清晰的)"},
    {id:700, q:"The child is very h_______ when playing with friends.", a:"happy (快乐的)"},
    {id:701, q:"We should a_______ the chance to learn from our mistakes.", a:"accept (接受/认可)"},
    {id:702, q:"The internet has changed our life d_______. (剧烈地/巨大地)", a:"drastically (剧烈地/彻底地)"},
    {id:703, q:"A b_______ person is one who is not afraid of danger.", a:"brave (勇敢的)"},
    {id:704, q:"We should c_______ our attention on what the teacher is saying.", a:"concentrate (集中)"},
    {id:705, q:"The flowers in the vase are f_______ and beautiful.", a:"fresh (鲜艳的/新鲜的)"},
    {id:706, q:"It's u_______ to judge a person only by their looks.", a:"unfair (不公平的)"},
    {id:707, q:"The police are looking for the t_______ who stole the car.", a:"thief (小偷)"},
    {id:708, q:"Reading can help us gain more k_______. (知识)", a:"knowledge (知识)"},
    {id:709, q:"We should d_______ the task into three parts.", a:"divide (划分/分配)"},
    {id:710, q:"A m_______ is a person who can perform magic tricks.", a:"magician (魔术师)"},
    {id:711, q:"It is i_______ for us to finish the project without any help.", a:"impossible (不可能的)"},
    {id:712, q:"The sun p_______ energy that is clean and free.", a:"provides (提供)"},
    {id:713, q:"We should be c_______ of our own words and actions.", a:"careful (小心的/留心的)"},
    {id:714, q:"The b_______ of nature is all around us.", a:"beauty (美/美丽)"},
    {id:715, q:"It's a p_______ for me to be invited to your wedding.", a:"pleasure (荣幸/乐事)"},
    {id:716, q:"The scientist made a great c_______ to the world of medicine.", a:"contribution (贡献)"},
    {id:717, q:"We should t_______ our best to help those in need.", a:"try (尽力/尝试)"},
    {id:718, q:"The water in the pool is very c_______ and cool.", a:"clear (清澈的)"},
    {id:719, q:"A j_______ is someone who works in a court of law.", a:"judge (法官)"},
    {id:720, q:"We should respect the c_______ of different people.", a:"choices (选择)"},
    {id:721, q:"The forest is a natural b_______ against sandstorms.", a:"barrier (屏障)"},
    {id:722, q:"It's necessary to have a b_______ between work and life.", a:"balance (平衡)"},
    {id:723, q:"We use a m_______ to look at the stars in the night sky.", a:"telescope (望远镜/此处m可对应magnifier放大镜)"},
    {id:723, q:"We use a m_______ to see tiny things more clearly.", a:"magnifier (放大镜)"},
    {id:724, q:"The teacher e_______ why the earth goes around the sun.", a:"explained (解释)"},
    {id:725, q:"It's a w_______ of time to argue with someone who won't listen.", a:"waste (浪费)"},
    {id:726, q:"We should cherish the m_______ we spent together.", a:"moments (时刻/时光)"},
    {id:727, q:"The stars are s_______ in the sky like diamonds.", a:"shining (闪烁)"},
    {id:728, q:"He is an o_______ student and always wins prizes.", a:"outstanding (优秀的/杰出的)"},
    {id:729, q:"The moon goes a_______ the earth every month.", a:"around (绕着)"},
    {id:730, q:"We should p_______ more trees to make the air fresher.", a:"plant (种植)"},
    {id:731, q:"The r_______ of the exam will be out tomorrow.", a:"results (结果)"},
    {id:732, q:"A s_______ is a person who serves in the army.", a:"soldier (士兵)"},
    {id:733, q:"We should d_______ more time to our hobbies.", a:"devote (投入)"},
    {id:734, q:"The fruit is very d_______ and juicy.", a:"delicious (美味的)"},
    {id:735, q:"It's a p_______ that I missed the early bus.", a:"pity (遗憾/可惜)"},
    {id:736, q:"The air in the forest is very f_______.", a:"fresh (新鲜的)"},
    {id:737, q:"We should t_______ the advice of our parents.", a:"take (接受/听取)"},
    {id:738, q:"The boy is very i_______ and can speak three languages.", a:"intelligent (聪明的)"},
    {id:739, q:"A d_______ is a person who treats sick animals.", a:"doctor (医生/此处d多指vet,但d对应dentist)"},
    {id:739, q:"A d_______ is someone who looks after your teeth.", a:"dentist (牙医)"},
    {id:740, q:"We should k_______ the environment clean for the next generation.", a:"keep (保持)"},
    {id:741, q:"The story is very m_______ and I can't stop reading it.", a:"moving (动人的/吸引人的)"},
    {id:742, q:"It's important to have a positive a_______ toward life.", a:"attitude (态度)"},
    {id:743, q:"The doctor is e_______ the patient in the room.", a:"examining (检查)"},
    {id:744, q:"We should use our t_______ wisely to learn more.", a:"time (时间)"},
    {id:745, q:"The fireworks display was very s_______. (壮观的)", a:"spectacular (壮观的)"},
    {id:746, q:"A v_______ is a person who works for free.", a:"volunteer (志愿者)"},
    {id:747, q:"We should c_______ our mistakes as soon as we find them.", a:"correct (改正)"},
    {id:748, q:"The book has a very s_______ ending.", a:"sad (悲伤的)"},
    {id:749, q:"The sun r_______ in the east and sets in the west.", a:"rises (升起)"},
    {id:750, q:"We should be k_______ to all the animals.", a:"kind (友善的)"},
    {id:751, q:"The train will a_______ at the station at 9 o'clock.", a:"arrive (到达)"},
    {id:752, q:"It's a w_______ of water to leave the tap running.", a:"waste (浪费)"},
    {id:753, q:"The scientist d_______ a new plant in the forest.", a:"discovered (发现)"},
    {id:754, q:"We should s_______ some money for the future.", a:"save (攒/省)"},
    {id:755, q:"The boy is very g_______ and always helps others.", a:"generous (慷慨的/大方的)"},
    {id:756, q:"A m_______ is a place where we see old things.", a:"museum (博物馆)"},
    {id:757, q:"We should p_______ our country with all our strength.", a:"protect (保护)"},
    {id:758, q:"The weather is very c_______ in autumn.", a:"cool (凉爽的)"},
    {id:759, q:"We use a k_______ to open the box.", a:"knife (小刀/此处k对应key也可)"},
    {id:760, q:"He is a f_______ singer and has many fans.", a:"famous (著名的)"},
    {id:761, q:"The earth is a p_______ that has life.", a:"planet (行星)"},
    {id:762, q:"We should s_______ energy by turning off the lights.", a:"save (节约)"},
    {id:763, q:"The stars are s_______ brightly tonight.", a:"shining (闪耀)"},
    {id:764, q:"A p_______ is someone who delivers newspapers.", a:"postman (邮递员)"},
    {id:765, q:"We should be g_______ for the food we have.", a:"grateful (感激的)"},
    {id:766, q:"The mountain is very h_______ and covered with snow.", a:"high (高的)"},
    {id:767, q:"It's i_______ to finish so much work in one day.", a:"impossible (不可能的)"},
    {id:768, q:"The driver should pay a_______ to the signs.", a:"attention (注意)"},
    {id:769, q:"We should e_______ the room when the bell rings.", a:"enter (进入/此处e对应empty)"},
    {id:769, q:"Please e_______ the bin every morning.", a:"empty (倒空)"},
    {id:770, q:"A c_______ is someone who makes delicious food.", a:"cook (厨师)"},
    {id:771, q:"The river f_______ through the city.", a:"flows (流过)"},
    {id:772, q:"It's a c_______ to wear red on festivals.", a:"custom (习俗)"},
    {id:773, q:"The girl can speak two l_______. (语言)", a:"languages (语言)"},
    {id:774, q:"We should protect our n_______ resources.", a:"natural (自然的)"},
    {id:775, q:"The stars are s_______ in the dark night.", a:"shining (闪烁)"},
    {id:776, q:"A j_______ is someone who works for a newspaper.", a:"journalist (记者)"},
    {id:777, q:"We should avoid throwing r_______ everywhere.", a:"rubbish (垃圾)"},
    {id:778, q:"The book is very u_______ for our English study.", a:"useful (有用的)"},
    {id:779, q:"The sun is s_______ in the west.", a:"setting (落下)"},
    {id:780, q:"We should l_______ a healthy life.", a:"lead (过着/引导)"},
    {id:781, q:"The flowers smell very f_______ after the rain.", a:"fresh (清新的)"},
    {id:782, q:"It's polite to o_______ help to others.", a:"offer (主动提供)"},
    {id:783, q:"The dog is the most f_______ friend to human.", a:"faithful (忠实的)"},
    {id:784, q:"We should keep our h_______ clean and tidy.", a:"house (房子/家)"},
    {id:785, q:"The moon reflects the l_______ of the sun.", a:"light (光)"},
    {id:786, q:"A s_______ is someone who studies science.", a:"scientist (科学家)"},
    {id:787, q:"We should reduce the a_______ of waste.", a:"amount (数量)"},
    {id:788, q:"The water will f_______ in the cold winter.", a:"freeze (结冰)"},
    {id:789, q:"It's a t_______ for us to have a big dinner on New Year's Eve.", a:"tradition (传统)"},
    {id:790, q:"We should b_______ our hair before going out.", a:"brush (梳理)"},
    {id:791, q:"The butterfly is a b_______ creature.", a:"beautiful (美丽的)"},
    {id:792, q:"We should be c_______ when we cross the street.", a:"careful (小心的)"},
    {id:793, q:"The airplane is a fast t_______ tool.", a:"transport (运输/交通)"},
    {id:794, q:"A p_______ is someone who works in a post office.", a:"postman (邮递员)"},
    {id:795, q:"We should s_______ our respect to the teachers.", a:"show (表现/展示)"},
    {id:796, q:"The wind is b_______ gently.", a:"blowing (吹)"},
    {id:797, q:"It's a g_______ to win the first prize.", a:"glory (光荣)"},
    {id:798, q:"The earth r_______ around the sun.", a:"revolves (旋转/公转)"},
    {id:799, q:"We should have a c_______ plan for our future.", a:"clear (清晰的)"},
    {id:800, q:"The child is playing with a t_______.", a:"toy (玩具)"},
    {id:801, q:"We should a_______ the rules of our school.", a:"abide (遵守/此处a也对应always)"},
    {id:801, q:"We must a_______ follow the law.", a:"always (总是)"},
    {id:802, q:"The Great Wall is a m_______ in the history of architecture.", a:"masterpiece (杰作/名作)"},
    {id:803, q:"A c_______ is a person who performs in a circus.", a:"clown (小丑)"},
    {id:804, q:"We should c_______ on our study to get good grades.", a:"concentrate (专注)"},
    {id:805, q:"The food is s_______ and delicious.", a:"sweet (甜的)"},
    {id:806, q:"It is u_______ to take away other people's things without asking.", a:"unjust (不公正的/不礼貌的)"},
    {id:807, q:"The police are chasing the c_______. (罪犯)", a:"criminal (罪犯)"},
    {id:808, q:"Reading can help us improve our s_______. (技能)", a:"skills (技能)"},
    {id:809, q:"We should d_______ the cake into several pieces.", a:"divide (切分)"},
    {id:810, q:"A m_______ is a person who creates beautiful music.", a:"musician (音乐家)"},
    {id:811, q:"It is i_______ for humans to live without oxygen.", a:"impossible (不可能的)"},
    {id:812, q:"The sun p_______ light for the moon to reflect.", a:"provides (提供)"},
    {id:813, q:"We should be c_______ with our money.", a:"careful (小心的/节约的)"},
    {id:814, q:"The b_______ of the rainbow is amazing.", a:"beauty (美)"},
    {id:815, q:"It's a p_______ to see you again.", a:"pleasure (乐事)"},
    {id:816, q:"The scientist made a d_______ about the universe.", a:"discovery (发现)"},
    {id:817, q:"We should t_______ our best to protect our home.", a:"try (努力)"},
    {id:818, q:"The water in the river is very p_______. (被污染的)", a:"polluted (被污染的)"},
    {id:819, q:"A j_______ is someone who writes stories for magazines.", a:"journalist (记者)"},
    {id:820, q:"We should respect the r_______ of others.", a:"rights (权利)"},
    {id:821, q:"The forest is a s_______ place for many birds.", a:"safe (安全的)"},
    {id:822, q:"It's necessary to keep the b_______ of the ecosystem.", a:"balance (平衡)"},
    {id:823, q:"We use a m_______ to look at small insects.", a:"magnifier (放大镜)"},
    {id:824, q:"The teacher e_______ how to use the computer.", a:"explained (解释)"},
    {id:825, q:"It's a w_______ of time to watch too much TV.", a:"waste (浪费)"},
    {id:826, q:"We should cherish our y_______ days.", a:"youth (青春/年轻)"},
    {id:827, q:"The stars are s_______ brightly in the sky.", a:"shining (闪烁)"},
    {id:828, q:"He is an o_______ student and gets top marks.", a:"outstanding (优秀的)"},
    {id:829, q:"The moon goes a_______ the earth.", a:"around (绕着)"},
    {id:830, q:"We should p_______ more trees to save the earth.", a:"plant (种植)"},
    {id:831, q:"The r_______ of the research were very surprising.", a:"results (结果)"},
    {id:832, q:"A s_______ is someone who works in a shop.", a:"shop-assistant (售货员)"},
    {id:833, q:"We should d_______ more time to our families.", a:"devote (投入)"},
    {id:834, q:"The food is very d_______, thank you.", a:"delicious (美味的)"},
    {id:835, q:"It's a p_______ that you can't come.", a:"pity (遗憾)"},
    {id:836, q:"The air is v_______ important for our life.", a:"very (非常)"},
    {id:837, q:"We should t_______ the advice of our teachers.", a:"take (接受)"},
    {id:838, q:"The boy is very i_______ and likes to read.", a:"intelligent (聪明的)"},
    {id:839, q:"A d_______ is someone who helps sick people.", a:"doctor (医生)"},
    {id:840, q:"We should k_______ the city clean.", a:"keep (保持)"},
    {id:841, q:"The story is very m_______ and sad.", a:"moving (动人的)"},
    {id:842, q:"It's important to have a positive a_______.", a:"attitude (态度)"},
    {id:843, q:"The doctor is e_______ the child now.", a:"examining (检查)"},
    {id:844, q:"We should use our e_______ wisely to work.", a:"energy (能量/精力)"},
    {id:845, q:"The fireworks display was very b_______. (美丽的)", a:"beautiful (美丽的)"},
    {id:846, q:"A v_______ is a person who helps others for free.", a:"volunteer (志愿者)"},
    {id:847, q:"We should c_______ the mistakes in our work.", a:"correct (纠正)"},
    {id:848, q:"The book has a h_______ ending.", a:"happy (快乐的)"},
    {id:849, q:"The sun r_______ in the east every day.", a:"rises (升起)"},
    {id:850, q:"We should be k_______ to our neighbors.", a:"kind (友好的)"},
    {id:851, q:"We should a_______ to our teacher when we make a mistake in class.", a:"apologize (道歉)"},
    {id:852, q:"The Great Wall is one of the most magnificent s_______ in the world.", a:"structures (建筑物/结构)"},
    {id:853, q:"A c_______ is a person who helps people with legal problems.", a:"consultant (顾问/咨询者)"},
    {id:854, q:"Please c_______ the information before you share it with others.", a:"confirm (确认)"},
    {id:855, q:"The flowers in the park are in full b_______ during spring.", a:"bloom (盛开)"},
    {id:856, q:"It is u_______ to expect everyone to agree with your opinion.", a:"unrealistic (不切实际的)"},
    {id:857, q:"The police are investigating the m_______ case carefully.", a:"mystery (神秘的/案件)"},
    {id:858, q:"Reading more books can help us improve our l_______ level.", a:"language (语言)"},
    {id:859, q:"We should d_______ our old books to the children in need.", a:"donate (捐赠)"},
    {id:860, q:"A m_______ is a device that can capture sound.", a:"microphone (麦克风)"},
    {id:861, q:"It is i_______ to drive a car without a license.", a:"illegal (违法的)"},
    {id:862, q:"The sun is the u_______ source of energy for all living things.", a:"ultimate (最终的/终极的)"},
    {id:863, q:"Be c_______ about what you post on social media.", a:"cautious (谨慎的)"},
    {id:864, q:"The b_______ of the landscape took our breath away.", a:"beauty (美丽)"},
    {id:865, q:"It's a p_______ to be part of this great project.", a:"privilege (荣幸/特权)"},
    {id:866, q:"The scientist's d_______ will change the way we live.", a:"discovery (发现)"},
    {id:867, q:"We should t_______ our best to protect the endangered species.", a:"try (努力/尝试)"},
    {id:868, q:"The water in the fountain is sparkling and c_______.", a:"clear (清澈的)"},
    {id:869, q:"A j_______ is a professional who writes for magazines.", a:"journalist (记者)"},
    {id:870, q:"We should respect the d_______ of different cultures.", a:"diversity (多样性)"},
    {id:871, q:"The forest acts as a natural s_______ against noise.", a:"shield (屏障/盾牌)"},
    {id:872, q:"It's necessary to maintain a b_______ between work and rest.", a:"balance (平衡)"},
    {id:873, q:"We use a m_______ to observe tiny bacteria.", a:"microscope (显微镜)"},
    {id:874, q:"The teacher e_______ the rules of the game clearly.", a:"explained (解释)"},
    {id:875, q:"It's a w_______ of energy to leave the heater on in an empty room.", a:"waste (浪费)"},
    {id:876, q:"We should cherish the f_______ we have with our classmates.", a:"friendship (友谊)"},
    {id:877, q:"The stars are s_______ in the galaxy.", a:"shining (闪耀)"},
    {id:878, q:"He is an o_______ athlete who has won many gold medals.", a:"outstanding (杰出的)"},
    {id:879, q:"The moon r_______ around the earth.", a:"revolves (旋转/绕转)"},
    {id:880, q:"We should p_______ more trees to combat climate change.", a:"plant (种植)"},
    {id:881, q:"The r_______ of the competition will be announced tonight.", a:"results (结果)"},
    {id:882, q:"A s_______ is a person who works on a ship.", a:"sailor (水手)"},
    {id:883, q:"We should d_______ more effort to our English learning.", a:"devote (投入)"},
    {id:884, q:"The dish is very d_______, my mother is a good cook.", a:"delicious (美味的)"},
    {id:885, q:"It's a p_______ that we couldn't go on a picnic because of the rain.", a:"pity (遗憾)"},
    {id:886, q:"The air is v_______ for our breathing.", a:"vital (至关重要的/极其重要的)"},
    {id:887, q:"We should t_______ the advice of the experts.", a:"take (采纳/听从)"},
    {id:888, q:"The boy is very i_______ and likes to explore new things.", a:"inquisitive (好奇的/爱钻研的)"},
    {id:889, q:"A d_______ is someone who takes care of people's teeth.", a:"dentist (牙医)"},
    {id:890, q:"We should k_______ the environment green.", a:"keep (保持)"},
    {id:891, q:"The movie is very m_______ and inspired many people.", a:"moving (动人的/感人的)"},
    {id:892, q:"It's important to have a positive a_______ toward challenges.", a:"attitude (态度)"},
    {id:893, q:"The doctor is e_______ the patient's heart.", a:"examining (检查)"},
    {id:894, q:"We should use our natural r_______ sustainably.", a:"resources (资源)"},
    {id:895, q:"The fireworks display was truly m_______.", a:"magnificent (宏伟的/壮观的)"},
    {id:896, q:"A v_______ is someone who offers to help without pay.", a:"volunteer (志愿者)"},
    {id:897, q:"We should c_______ our mistakes to improve ourselves.", a:"correct (纠正)"},
    {id:898, q:"The story has a very h_______ and warm ending.", a:"happy (幸福的)"},
    {id:899, q:"The sun r_______ in the east every morning.", a:"rises (升起)"},
    {id:900, q:"We should be k_______ and helpful to the elderly.", a:"kind (善良的)"},
    {id:901, q:"We should a_______ our goals through hard work.", a:"achieve (实现/达到)"},
    {id:902, q:"The Great Wall is a famous t_______ attraction.", a:"tourist (旅游)"},
    {id:903, q:"A c_______ is someone who is in charge of a ship.", a:"captain (船长)"},
    {id:904, q:"We should c_______ on our strengths rather than our weaknesses.", a:"concentrate (集中/关注)"},
    {id:905, q:"The cake is very s_______ and soft.", a:"sweet (甜的)"},
    {id:906, q:"It's u_______ to judge people before you get to know them.", a:"unwise (不明智的/不公平的)"},
    {id:907, q:"The police p_______ the city from crime.", a:"protect (保护)"},
    {id:908, q:"Reading can help us broaden our h_______. (视野)", a:"horizons (视野/眼界)"},
    {id:909, q:"We should d_______ our time between study and hobbies.", a:"divide (分配/划分)"},
    {id:910, q:"A m_______ is a scientist who studies math.", a:"mathematician (数学家)"},
    {id:911, q:"It's i_______ for a person to fly like a bird.", a:"impossible (不可能的)"},
    {id:912, q:"The sun p_______ light for the Earth.", a:"provides (提供)"},
    {id:913, q:"We should be c_______ of our surroundings.", a:"conscious (自觉的/意识到的)"},
    {id:914, q:"The b_______ of the flowers is so attractive.", a:"beauty (美丽)"},
    {id:915, q:"It's a p_______ to meet you here today.", a:"pleasure (荣幸)"},
    {id:916, q:"The scientist made a major b_______ in cancer research.", a:"breakthrough (突破)"},
    {id:917, q:"We should t_______ our best to learn a second language.", a:"try (尝试/努力)"},
    {id:918, q:"The water in the lake is so c_______ that you can see the bottom.", a:"clear (清澈的)"},
    {id:919, q:"A j_______ is someone who judges in a competition.", a:"judge (评委/裁判)"},
    {id:920, q:"We should respect the p_______ of others.", a:"privacy (隐私)"},
    {id:921, q:"The forest is a natural h_______ for many species.", a:"habitat (栖息地)"},
    {id:922, q:"It's important to keep a b_______ diet.", a:"balanced (平衡的/均衡的)"},
    {id:923, q:"We use a m_______ to look at small things.", a:"magnifier (放大镜)"},
    {id:924, q:"The teacher e_______ the meaning of the word.", a:"explained (解释)"},
    {id:925, q:"It's a w_______ of time to watch too much TV.", a:"waste (浪费)"},
    {id:926, q:"We should cherish our f_______ and family.", a:"friends (朋友)"},
    {id:927, q:"The stars are s_______ in the dark sky.", a:"shining (闪亮)"},
    {id:928, q:"He is an o_______ student and gets high grades.", a:"outstanding (优秀的)"},
    {id:929, q:"The moon goes a_______ the earth every day.", a:"around (绕着)"},
    {id:930, q:"We should p_______ more trees to make the world green.", a:"plant (种植)"},
    {id:931, q:"The r_______ of the game was 3-2.", a:"result (结果)"},
    {id:932, q:"A s_______ is a person who serves customers in a store.", a:"shop-assistant (店员)"},
    {id:933, q:"We should d_______ more time to helping others.", a:"devote (投入)"},
    {id:934, q:"The food is very d_______, I like it very much.", a:"delicious (美味的)"},
    {id:935, q:"It's a p_______ that you can't join us.", a:"pity (遗憾)"},
    {id:936, q:"The air is v_______ for all living things.", a:"vital (至关重要的)"},
    {id:937, q:"We should t_______ the advice of our elders.", a:"take (采纳)"},
    {id:938, q:"The boy is very i_______ and likes to learn.", a:"intelligent (聪明的)"},
    {id:939, q:"A d_______ is a person who helps sick people.", a:"doctor (医生)"},
    {id:940, q:"We should k_______ the classroom clean.", a:"keep (保持)"},
    {id:941, q:"The story is very m_______ and makes me cry.", a:"moving (动人的)"},
    {id:942, q:"It's important to have a positive a_______ toward study.", a:"attitude (态度)"},
    {id:943, q:"The doctor is e_______ the patient now.", a:"examining (检查)"},
    {id:944, q:"We should use our energy w_______. (明智地)", a:"wisely (明智地)"},
    {id:945, q:"The fireworks display was very b_______.", a:"beautiful (美丽的)"},
    {id:946, q:"A v_______ is a person who works for free.", a:"volunteer (志愿者)"},
    {id:947, q:"We should c_______ our errors in the test.", a:"correct (更正)"},
    {id:948, q:"The book has a h_______ ending, everyone is glad.", a:"happy (快乐的)"},
    {id:949, q:"The sun r_______ in the east.", a:"rises (升起)"},
    {id:950, q:"We should be k_______ to our friends.", a:"kind (友好的)"},
    {id:951, q:"We should a_______ the problem before we solve it.", a:"analyze (分析)"},
    {id:952, q:"The Great Wall is a g_______ architecture in China.", a:"great (伟大的/宏伟的)"},
    {id:953, q:"A c_______ is someone who fixes cars.", a:"car-mechanic (汽车修理工)"},
    {id:954, q:"We should c_______ our attention on the lesson.", a:"concentrate (集中)"},
    {id:955, q:"The apple is very s_______ and crunchy.", a:"sweet (甜的)"},
    {id:956, q:"It's u_______ to lie to your friends.", a:"unwise (不明智的/不对的)"},
    {id:957, q:"The police p_______ the neighborhood.", a:"patrol (巡逻)"},
    {id:958, q:"Reading more books can help us improve our v_______. (词汇量)", a:"vocabulary (词汇量)"},
    {id:959, q:"We should d_______ our time to different subjects.", a:"devote (投入/分配)"},
    {id:960, q:"A m_______ is someone who works in a mine.", a:"miner (矿工)"},
    {id:961, q:"It's i_______ for us to live without water.", a:"impossible (不可能的)"},
    {id:962, q:"The sun p_______ light for the planets.", a:"provides (提供)"},
    {id:963, q:"We should be c_______ when we are driving.", a:"careful (小心的)"},
    {id:964, q:"The b_______ of nature is unlimited.", a:"beauty (美)"},
    {id:965, q:"It's a p_______ to meet such a famous person.", a:"pleasure (荣幸)"},
    {id:966, q:"The scientist's d_______ was reported in the news.", a:"discovery (发现)"},
    {id:967, q:"We should t_______ our best to help the poor.", a:"try (努力)"},
    {id:968, q:"The water in the river is very c_______ today.", a:"clear (清澈的)"},
    {id:969, q:"A j_______ is someone who writes for newspapers.", a:"journalist (记者)"},
    {id:970, q:"We should respect the r_______ of every child.", a:"rights (权利)"},
    {id:971, q:"The forest is the h_______ of many birds.", a:"home (家园)"},
    {id:972, q:"It's necessary to have a b_______ life.", a:"balanced (平衡的)"},
    {id:973, q:"We use a m_______ to look at very small objects.", a:"microscope (显微镜)"},
    {id:974, q:"The teacher e_______ the lesson again.", a:"explained (解释)"},
    {id:975, q:"It's a w_______ of energy to leave the TV on.", a:"waste (浪费)"},
    {id:976, q:"We should cherish our y_______.", a:"youth (青春)"},
    {id:977, q:"The stars are s_______ in the sky tonight.", a:"shining (闪亮)"},
    {id:978, q:"He is an o_______ student and gets top grades.", a:"outstanding (优秀的)"},
    {id:979, q:"The moon goes a_______ the earth.", a:"around (绕着)"},
    {id:980, q:"We should p_______ more trees to protect the soil.", a:"plant (种植)"},
    {id:981, q:"The r_______ of the test were released.", a:"results (结果)"},
    {id:982, q:"A s_______ is a person who designs clothes.", a:"stylist (造型师/设计师)"},
    {id:983, q:"We should d_______ more time to our studies.", a:"devote (投入)"},
    {id:984, q:"The meal is very d_______, thank you.", a:"delicious (美味的)"},
    {id:985, q:"It's a p_______ that you can't come to the party.", a:"pity (遗憾)"},
    {id:986, q:"The air is v_______ for our survival.", a:"vital (至关重要的)"},
    {id:987, q:"We should t_______ the advice of the doctor.", a:"take (采取/采纳)"},
    {id:988, q:"The boy is very i_______ and likes to explore.", a:"intelligent (聪明的)"},
    {id:989, q:"A d_______ is someone who helps people with their health.", a:"doctor (医生)"},
    {id:990, q:"We should k_______ our environment clean.", a:"keep (保持)"},
    {id:991, q:"The story is very m_______ and has a good moral.", a:"moving (动人的)"},
    {id:992, q:"It's important to have a positive a_______ toward everything.", a:"attitude (态度)"},
    {id:993, q:"The doctor is e_______ the patient's eyes.", a:"examining (检查)"},
    {id:994, q:"We should use our time w_______. (明智地)", a:"wisely (明智地)"},
    {id:995, q:"The fireworks display was very b_______.", a:"beautiful (美丽的)"},
    {id:996, q:"A v_______ is someone who works for a charity.", a:"volunteer (志愿者)"},
    {id:997, q:"We should c_______ our homework before handing it in.", a:"check (检查/纠正)"},
    {id:998, q:"The book has a v_______ interesting plot.", a:"very (非常)"},
    {id:999, q:"The sun r_______ and sets every day.", a:"rises (升起)"},
    {id:1000, q:"Knowledge is p_______. (知识就是力量)", a:"power (力量)"}
];