// 这个文件是你的题库数据库。
// 格式：{id: 题目编号, q: "题目内容", a: "标准答案（多空用逗号隔开）"}
// 你可以随时用记事本或 VS Code 打开并修改、添加题目。

const database = [
    {id:1, q:"All the children are very e_______ about the firework.", a:"excited"},
    {id:2, q:"Helen w_______ to school everyday.", a:"walks"},
    {id:3, q:"Miss Li and her students are t_______ about their plans for the party.", a:"talking"},
    {id:4, q:"Nancy is a new student in my class. I want to s_______ her around our school.", a:"show"},
    {id:5, q:"Anna is helping her mother c_______ jiaozi in the kitchen.", a:"cook"},
    {id:6, q:"Mary u_______ an English-Chinese Dictionary to learn the new words.", a:"uses"},
    {id:7, q:"Be c_______! There are some elephants in front of you.", a:"careful"},
    {id:8, q:"Mr Bai is not a r_______ man. But he sends all of his money to help the students keep studying.", a:"rich"},
    {id:9, q:"M_______ are good places to let people know the old s_______ of a city or a country.", a:"Museums, stories"},
    {id:10, q:"Sam told Bobby to be c_______ on the ice. But Bobby didn’t listen to Sam and fell into the ice h_______.", a:"careful, hole"},
    {id:11, q:"Mr Li is in the teachers’ o_______. He is correcting his students’ h_______.", a:"office, homework"},
    {id:12, q:"David, your arm is black and blue. What h_______ this morning?", a:"happened"},
    {id:13, q:"My father likes w_______ football matches with his friends at weekends.", a:"watching"},
    {id:14, q:"Can I a_______ you a question?", a:"ask"},
    {id:15, q:"They are the children of your son or daughter. They’re your g_______.", a:"grandchildren"},
    {id:16, q:"What places are you going to v_______ a_______ Spring Festival?", a:"visit, at"},
    {id:17, q:"Bobby g_______ a lot red packets, he thought he was rich.", a:"got"},
    {id:18, q:"They’re talking about their p_______ for the weekend.", a:"plans"},
    {id:19, q:"We can use some w_______ to make a tree house in the forest.", a:"wood"},
    {id:20, q:"Don’t drink too m_______ cola, Tim. There’s a lot of sugar in it.", a:"much"},
    {id:21, q:"My grandma likes c_______ plastic bags. She often cleans them and r_______ them.", a:"collecting, reuses"},
    {id:22, q:"We shouldn’t w_______ water, we should r_______ it.", a:"waste, reuse"},
    {id:23, q:"Bobby likes l_______ in the city.", a:"living"},
    {id:24, q:"Most of our energy comes from coal and o_______.", a:"oil"},
    {id:25, q:"My father always d_______ a car to work.", a:"drives"},
    {id:26, q:"R_______ is bad for the Earth.", a:"Rubbish"},
    {id:27, q:"Please t_______ these packing bags into the bin.", a:"throw"},
    {id:28, q:"Look! They are c_______ down the trees.", a:"cutting"},
    {id:29, q:"There are not so many forests in the world. So we shouldn’t use too much w_______.", a:"wood"},
    {id:30, q:"We are doing a p_______ about “How to protect animals.” It’s great f_______.", a:"project, fun"},
    {id:31, q:"The Earth is our h_______. We should p_______ it.", a:"home, protect"},
    {id:32, q:"—Does your mother usually s_______ money? —Yes, she does.", a:"save"},
    {id:33, q:"Go and ask Sam for help. He always has some good i_______.", a:"ideas"},
    {id:34, q:"We can see many old and interesting things in the m_______.", a:"museum"},
    {id:35, q:"I didn’t s_______ well last night because of the noise f_______ that factory.", a:"sleep, from"},
    {id:36, q:"P_______ more trees can help keep the air clean.", a:"Planting"},
    {id:37, q:"The river was not clean. There were a lot of d_______ fish in it.", a:"dead"},
    {id:38, q:"Rubbish makes the streets m_______ and dirty.", a:"messy"},
    {id:39, q:"Smoke and rubbish m_______ our city dirty.", a:"make"},
    {id:40, q:"To keep our school clean, we should s_______ the floor regularly (经常).", a:"sweep"},
    {id:41, q:"Don’t throw the banana skin on the g_______. Someone may slip on it.", a:"ground"},
    {id:42, q:"Smoke makes the air d_______.", a:"dirty"},
    {id:43, q:"Mike, your room is d_______ and messy. Please c_______ it now.", a:"dirty, clean"},
    {id:44, q:"You shouldn’t s_______ here. It’s bad for our health.", a:"smoke"},
    {id:45, q:"Let’s buy things in the shopping c_______.", a:"centre"},
    {id:46, q:"The sign by the river m_______ “Danger”.", a:"means"},
    {id:47, q:"Jack feels h_______, because today is his birthday.", a:"happy"},
    {id:48, q:"There are many trees a_______ the house.", a:"around"},
    {id:49, q:"My family often have dinner in the r_______.", a:"restaurant"},
    {id:50, q:"The girl p_______ at the photo and shouted, “Look! This is me!”", a:"pointed"},
    {id:51, q:"I s_______ a fashion show with my parents in the school hall yesterday.", a:"saw"},
    {id:52, q:"Mrs White didn’t b_______ many things in the supermarket yesterday morning.", a:"buy"},
    {id:53, q:"Mike got up late this morning. So he had to wait for the n_______ bus.", a:"next"},
    {id:54, q:"—Why are you l_______? —Because I’m reading a very interesting story.", a:"laughing"},
    {id:55, q:"Tom, can you make a sentence w_______ “honey”?", a:"with"},
    {id:56, q:"My grandpa reads n_______ for news.", a:"newspapers"},
    {id:57, q:"Did you c_______ a big fish on the farm?", a:"catch"},
    {id:58, q:"Mrs Brown often does s_______ on the Internet. She buys many things every year.", a:"shopping"},
    {id:59, q:"—Can you s_______ the word “Tuesday”? —Yes, T-u-e-s-d-a-y, Tuesday.", a:"spell"},
    {id:60, q:"Our English teacher is calling people in her o_______.", a:"office"},
    {id:61, q:"My father t_______ me a story every night.", a:"tells"},
    {id:62, q:"The coat is not big or small. It f_______ me very well.", a:"fits"},
    {id:63, q:"Ten years a_______, I could not write. Now I can write well.", a:"ago"},
    {id:64, q:"We can call people a_______ with a mobile phone.", a:"anywhere"},
    {id:65, q:"Miss Black l_______ to some music before sleeping every night.", a:"listens"},
    {id:66, q:"It’s eleven o’clock at night now. Tom is s_______ doing his homework.", a:"still"},
    {id:67, q:"The t_______ is ringing. Please answer it, Helen.", a:"telephone"},
    {id:68, q:"George got an e_______ from his e_______ John this morning.", a:"email, e-friend"},
    {id:69, q:"Can you a_______ my question?", a:"answer"},
    {id:70, q:"Twenty years ago, we used telephones to c_______ people.", a:"call"},
    {id:71, q:"At f_______, the basketball match went well.", a:"first"},
    {id:72, q:"We have a seven-day h_______ at the Spring Festival.", a:"holiday"},
    {id:73, q:"We usually have a long h_______ in summer.", a:"holiday"},
    {id:74, q:"—Look, Sam is wearing a lot of b_______. —He looks so funny.", a:"badges"},
    {id:75, q:"There was a puppet s_______ this morning. It was w_______.", a:"show, wonderful"},
    {id:76, q:"Liu Tao s_______ many i_______ things in the Shanghai Museum that day.", a:"saw, interesting"},
    {id:77, q:"There are many white c_______ in the sky.", a:"clouds"},
    {id:78, q:"The weather b_______ windy a moment ago.", a:"became"},
    {id:79, q:"Sam, it is your t_______ to make a sentence now.", a:"turn"},
    {id:80, q:"Long long ago, there was a k_______. He liked clothes very much.", a:"king"},
    {id:81, q:"The T-shirt is just right. It f_______ me.", a:"fits"},
    {id:82, q:"The queen walked t_______ the city with the k_______.", a:"through, king"},
    {id:83, q:"Be q_______, Mike! It’s late.", a:"quick"},
    {id:84, q:"We had a w_______ time at the show last night.", a:"wonderful"},
    {id:85, q:"You are very quiet, Sam. What are you t_______?", a:"thinking"},
    {id:86, q:"Lily is very c_______. She always does well in her lessons.", a:"clever"},
    {id:87, q:"Su Hai was happy to s_______ her beautiful clothes to us.", a:"show"},
    {id:88, q:"Helen b_______ a new dress from that shop yesterday.", a:"bought"},
    {id:89, q:"They say f_______ people can’t see the new clothes.", a:"foolish"},
    {id:90, q:"My mother liked w_______ red clothes ten years ago.", a:"wearing"},
    {id:91, q:"My parents are going to g_______ me red packets on Chinese New Year’s Day.", a:"give"},
    {id:92, q:"The police p_______ us from danger in our city.", a:"protect"},
    {id:93, q:"We shouldn’t use too much plastic, we should use g_______ bottles.", a:"glass"},
    {id:94, q:"Let me d_______ some trees and f_______ on the paper.", a:"draw, flowers"},
    {id:95, q:"We shouldn’t w_______ time. We should s_______ it.", a:"waste, save"},
    {id:96, q:"There is not m_______ energy on Earth.", a:"much"},
    {id:97, q:"Don’t d_______ so much, because cars use lots of e_______.", a:"drive, energy"},
    {id:98, q:"Don’t worry. I can h_______ you.", a:"help"}
    {id:101, q:"We should r_______ paper and bottles to save energy.", a:"recycle"},
    {id:102, q:"It's i_______ to keep our promises to others.", a:"important"},
    {id:103, q:"Don't be a_______ of the dog. It is very friendly.", a:"afraid"},
    {id:104, q:"The library is a q_______ place. Please don't make any noise.", a:"quiet"},
    {id:105, q:"There are many d_______ kinds of flowers in the park.", a:"different"},
    {id:106, q:"I often b_______ books from the school library.", a:"borrow"},
    {id:107, q:"The soup t_______ delicious. Did you make it yourself?", a:"tastes"},
    {id:108, q:"The b_______ over the river is very long and beautiful.", a:"bridge"},
    {id:109, q:"We should brush our t_______ twice a day to keep them healthy.", a:"teeth"},
    {id:110, q:"W_______ is the fourth day of a week.", a:"Wednesday"},
    {id:111, q:"He is s_______ enough to lift the heavy box.", a:"strong"},
    {id:112, q:"The plane will t_______ o_______ in ten minutes. Please sit down.", a:"take, off"},
    {id:113, q:"Could you please t_______ o_______ the light? I want to sleep.", a:"turn, off"},
    {id:114, q:"The sun r_______ in the east and sets in the west every day.", a:"rises"},
    {id:115, q:"He looks u_______ because he failed his English exam.", a:"unhappy"},
    {id:116, q:"F_______ is the second month of a year.", a:"February"},
    {id:117, q:"We should take care of the e_______ animals, like pandas.", a:"endangered"},
    {id:118, q:"Please fill in the blanks w_______ the correct words.", a:"with"},
    {id:119, q:"My dream is to travel a_______ the world in the future.", a:"around"},
    {id:120, q:"He is i_______ in playing the violin and the piano.", a:"interested"},
    {id:121, q:"I am h_______, let's go to the r_______ for lunch.", a:"hungry, restaurant"},
    {id:122, q:"The f_______ is very thick, we can't see the road clearly.", a:"fog"},
    {id:123, q:"Success comes from h_______ w_______ every day.", a:"hard, work"},
    {id:124, q:"You should listen to the teacher c_______ in class.", a:"carefully"},
    {id:125, q:"There is a 'No L_______' sign here. You can't throw rubbish.", a:"Littering"},
    {id:126, q:"Smoking is b_______ for our health.", a:"bad"},
    {id:127, q:"My father always r_______ a newspaper after dinner.", a:"reads"},
    {id:128, q:"Autumn is my f_______ season because it's cool.", a:"favourite"},
    {id:129, q:"The elephant is the l_______ animal on land.", a:"largest"},
    {id:130, q:"We can b_______ a hole in the ground to plant a tree.", a:"bury"},
    {id:131, q:"Please be p_______ when you wait for the bus.", a:"patient"},
    {id:132, q:"The boy is very h_______, he always helps old people.", a:"helpful"},
    {id:133, q:"In the past, people didn't have m_______ phones to call.", a:"mobile"},
    {id:134, q:"The Great Wall is one of the most famous p_______ in China.", a:"places"},
    {id:135, q:"We should stop people from c_______ down too many trees.", a:"cutting"},
    {id:136, q:"The air is f_______ and clean in the countryside.", a:"fresh"},
    {id:137, q:"—How o_______ do you go to the cinema? —Once a month.", a:"often"},
    {id:138, q:"It's polite to say 'Thank you' when someone h_______ you.", a:"helps"},
    {id:139, q:"The c_______ is a place where many children study.", a:"classroom"},
    {id:140, q:"The earth is getting warmer and w_______. It's a problem.", a:"warmer"},
    {id:141, q:"Turn r_______ at the first crossing, you'll see the bank.", a:"right"},
    {id:142, q:"We can use the i_______ to find a lot of information.", a:"Internet"},
    {id:143, q:"Don't forget to l_______ the door when you leave.", a:"lock"},
    {id:144, q:"Water is n_______ for all living things.", a:"necessary"},
    {id:145, q:"My brother wants to be an a_______ and fly to the moon.", a:"astronaut"},
    {id:146, q:"Keep away from the d_______ water! You can't swim here.", a:"deep"},
    {id:147, q:"S_______ is the last day of the week.", a:"Saturday"},
    {id:148, q:"A c_______ is an animal that has a long neck.", a:"giraffe"},
    {id:149, q:"My mother is a n_______. She works in a hospital.", a:"nurse"},
    {id:150, q:"Please s_______ the floor. It's a bit dirty.", a:"sweep"},
    {id:151, q:"We should learn how to p_______ our environment.", a:"protect"},
    {id:152, q:"The supermarket is usually c_______ on Sundays.", a:"crowded"},
    {id:153, q:"A k_______ is a person who rules a country.", a:"king"},
    {id:154, q:"Would you like to join our English c_______?", a:"club"},
    {id:155, q:"The cake is s_______ and delicious. I like it.", a:"sweet"},
    {id:156, q:"Yesterday was r_______, so we stayed at home.", a:"rainy"},
    {id:157, q:"He is l_______ to his favorite songs now.", a:"listening"},
    {id:158, q:"The kitchen is the place for c_______ food.", a:"cooking"},
    {id:159, q:"I have a headache. I must see a d_______.", a:"doctor"},
    {id:160, q:"The moon goes a_______ the earth.", a:"around"},
    {id:161, q:"Be c_______ when you cross the busy street.", a:"careful"},
    {id:162, q:"We should save w_______ because it's limited.", a:"water"},
    {id:163, q:"My pen is lost. I can't find it a_______.", a:"anywhere"},
    {id:164, q:"The farmer has many sheep and c_______ on his farm.", a:"cows"},
    {id:165, q:"The sign says 'No P_______'. You can't leave your car here.", a:"Parking"},
    {id:166, q:"The wind is blowing s_______. It's cold outside.", a:"strongly"},
    {id:167, q:"Children are the f_______ of our country.", a:"future"},
    {id:168, q:"He is good at m_______ things with his hands.", a:"making"},
    {id:169, q:"My parents gave me a s_______ on my birthday.", a:"surprise"},
    {id:170, q:"Birds can fly high in the s_______.", a:"sky"},
    {id:171, q:"The shop sells m_______ kinds of fruit and vegetables.", a:"many"},
    {id:172, q:"You should brush your teeth b_______ you go to bed.", a:"before"},
    {id:173, q:"We can see many stars at n_______.", a:"night"},
    {id:174, q:"The river is too wide to s_______ across.", a:"swim"},
    {id:175, q:"My uncle is a p_______ officer. He is very brave.", a:"police"},
    {id:176, q:"Green plants can make the air c_______.", a:"clean"},
    {id:177, q:"The film is very b_______. I want to sleep.", a:"boring"},
    {id:178, q:"Summer is the h_______ season of the year.", a:"hottest"},
    {id:179, q:"Please wait a m_______, I'll be back soon.", a:"moment"},
    {id:180, q:"We can go to the z_______ to see tigers and lions.", a:"zoo"},
    {id:181, q:"My computer is b_______. I need to fix it.", a:"broken"},
    {id:182, q:"Plastic bags are harmful to the E_______.", a:"Earth"},
    {id:183, q:"We can reuse the b_______ to store things.", a:"bottles"},
    {id:184, q:"I u_______ get up at six in the morning.", a:"usually"},
    {id:185, q:"Spring is a lovely season. F_______ come out.", a:"Flowers"},
    {id:186, q:"Can you tell me the way to the railway s_______?", a:"station"},
    {id:187, q:"The orange is juicy and s_______. I love it.", a:"sweet"},
    {id:188, q:"My hobby is c_______ stamps from different countries.", a:"collecting"},
    {id:189, q:"We should t_______ off the tap when we finish washing.", a:"turn"},
    {id:190, q:"Reading more books can make us c_______.", a:"clever"},
    {id:191, q:"The rabbit has long e_______ and a short tail.", a:"ears"},
    {id:192, q:"Look! The children are playing h_______ in the playground.", a:"happily"},
    {id:193, q:"Don't w_______ too much energy in your daily life.", a:"waste"},
    {id:194, q:"He s_______ an hour doing his homework yesterday.", a:"spent"},
    {id:195, q:"There are sixty m_______ in an hour.", a:"minutes"},
    {id:196, q:"The post office is b_______ the school and the park.", a:"between"},
    {id:197, q:"Would you please give me a h_______? This box is heavy.", a:"hand"},
    {id:198, q:"My grandparents live in a small v_______ near the sea.", a:"village"},
    {id:199, q:"We are p_______ of our great country.", a:"proud"},
    {id:200, q:"Eat more v_______ and you will be healthy.", a:"vegetables"}
];